using System.Collections.Generic;
using SortPaint.Core;

namespace SortPaint.Tests;

/// <summary>
/// The shipped pictures, mirrored from scripts/make_level_sprites.py in lowercase. Keep the two
/// in step: the art here is what proves a level can still be scrambled and finished.
/// </summary>
internal static class LevelSprites
{
    public static readonly string[] Toadstool =
    [
        "................",
        ".....oooooo.....",
        "...oorrrrrroo...",
        "..orwwrrrrwwro..",
        ".orrwwrrrrwwrro.",
        ".orrrrrrrrrrddo.",
        "oorrrrwwwwrrdddo",
        "orrwrrwwwwrrwddo",
        "orrwrrrwwrrrwddo",
        "oooooooooooooooo",
        "...osssssssso...",
        "...osoossooso...",
        "...osoossooso...",
        "...osssssstto...",
        "...osssssttto...",
        "....oooooooo....",
    ];

    public static readonly string[] Cherries =
    [
        "................",
        "..........gg....",
        ".........gggn...",
        "........ggnn....",
        ".......ggg......",
        ".......g.g......",
        "......g...g.....",
        ".....g.....g....",
        "....g.......g...",
        "...g........g...",
        "..ooo......ooo..",
        ".orrro....orrro.",
        "orwrrdo..orwrrdo",
        "orrrrdo..orrrrdo",
        ".orrdo....orrdo.",
        "..ooo......ooo..",
    ];

    public static readonly string[] Balloon =
    [
        "................",
        "......oooo......",
        "....oybbbbyo....",
        "...oyybbbbyyo...",
        "..oryybbbbyyro..",
        ".orryybbbbyyrro.",
        ".orryybbbbyyrro.",
        "..oryybbbbyyro..",
        "...oyybbbbyyo...",
        "....oybbbbyo....",
        ".....oooooo.....",
        "......e..e......",
        ".....okkkko.....",
        ".....okkeeo.....",
        ".....oooooo.....",
        "................",
    ];

    public static readonly string[] Sailboat =
    [
        "................",
        "........k.......",
        ".......wk.......",
        "......wwkr......",
        ".....wwwkrr.....",
        "....wwwwkrrr....",
        "...wwwwwkrrrr...",
        "..wwwwwwkrrrr...",
        ".wwwwwwwkrrrrr..",
        ".wwwwwwwkrrrrr..",
        "..oooooooooooo..",
        "..okkkkkkkkkko..",
        "...okkkkkkkko...",
        "....oooooooo....",
        "bccbbbccbbbccbbb",
        "bbbbbbbbbbbbbbbb",
    ];

    public static readonly string[] Cactus =
    [
        ".......pp.......",
        "......gppn......",
        "......ggnn......",
        "......ggnn......",
        "..ppn.ggnn......",
        "..ggn.ggnn.ppn..",
        "..ggn.ggnn.ggn..",
        "..ggn.ggnn.ggn..",
        "..ggggggnn.ggn..",
        "......ggggggnn..",
        "......ggnn......",
        "......ggnn......",
        "...kkkkkkkkke...",
        "....kkkkkkke....",
        "....kkkkkkee....",
        ".....eeeeee.....",
    ];

    public static readonly string[] Rocket =
    [
        ".......oo.......",
        "......orro......",
        "......orro......",
        ".....orrrro.....",
        ".....ollllo.....",
        ".....olcclo.....",
        ".....olcclo.....",
        ".....ollllo.....",
        "...orolllloro...",
        "..orrollllorro..",
        ".orrrollllorrro.",
        ".ooooollllooooo.",
        ".....oooooo.....",
        "......yyyy......",
        "......yaay......",
        ".......aa.......",
    ];

    public static readonly string[] Lion =
    [
        "........................",
        "...oo.oooooooooooo.oo...",
        "..oaaooaaaaaaaaaaooaao..",
        "..oaaaaaaaaaaaaaaaaaao..",
        "..oaaaaaaaaaaaaaaaaaao..",
        "..oaaaooooooooooooaaao..",
        ".oaaaossssssssssssoaaao.",
        ".oaaaossssssssssssoaaao.",
        ".oaaosswwsssssswwssoaao.",
        ".oaaosswossssssowssoaao.",
        ".oaaossssssssssssssoaao.",
        ".oaaossssoooooossssoaao.",
        ".oaaaossssottossssoaaao.",
        "..oaaaossttttttssoaaao..",
        "..oaaaaossssssssoaaaao..",
        "...oaaaaaaaaaaaaaaaao...",
        "....ooaaaaaaaaaaaaoo....",
        "......ooaaaaaaaaoo......",
        ".......osssssssso.......",
        "......osssssssssso......",
        "......osssssssssso......",
        ".......osssssssso.......",
        "........oooooooo........",
        "........................",
    ];

    public static readonly string[] Tiger =
    [
        "........................",
        "........................",
        "....oooo........oooo....",
        "...oaaaao......oaaaao...",
        "...oaooaooooooooaooao...",
        "...oaaaoaaaaaaaaoaaao...",
        "....oooaaoaaaaoaaooo....",
        "...ooaaaaaaaaaaaaaaoo...",
        "..oaaoaaaoaaaaoaaaoaao..",
        "..oaaawwoaaaaaaowwaaao..",
        "..oaaawooaaaaaaoowaaao..",
        "..oaaoaaassssssaaaoaao..",
        "..oaaoaasssoosssaaoaao..",
        "...oaaassssoossssaaao...",
        "...oaaoasswwwwssaoaao...",
        "....oaaassssssssaaao....",
        ".....ooaaoaaaaoaaoo.....",
        "......osssssssssso......",
        ".....oassssssssssao.....",
        ".....oaaossssssoaao.....",
        ".....oaaassssssaaao.....",
        "......oaaoaaaaoaao......",
        ".......oooooooooo.......",
        "........................",
    ];

    public static readonly string[] Elephant =
    [
        "........................",
        "........................",
        "..oooooo........oooooo..",
        ".olllllloooooooollllllo.",
        ".ollllllommmmmmollllllo.",
        ".ollllllommmmmmollllllo.",
        ".ollllllmmmmmmmmllllllo.",
        ".ollllllmwwmmwwmllllllo.",
        ".ollllllmwommowmllllllo.",
        ".ollllllmmmmmmmmllllllo.",
        ".ollllllmmmmmmmmllllllo.",
        ".ollllllmmmmmmmmllllllo.",
        ".ollllllmmmmmmmmllllllo.",
        "..ollllommmmmmmmollllo..",
        "...ooooommmmmmmmooooo...",
        "......wwommmmmmoww......",
        "......wwommmmmmoww......",
        ".......wommmmmmow.......",
        "........ommmmmmo........",
        "........ommmmmmo........",
        ".........ommmmo.........",
        ".........ommmmo.........",
        "..........oooo..........",
        "........................",
    ];

    public static readonly string[] Giraffe =
    [
        "........................",
        "..............oo.oo.....",
        "..............okoko.....",
        ".............oosssoo....",
        ".............ossssso....",
        ".............osososo....",
        ".............ossssso....",
        ".............oosssoo....",
        "..............ossko.....",
        "..............oksso.....",
        "..............ossso.....",
        "..............oskso.....",
        "..............ossso.....",
        "......ooooooooosskoo....",
        "......osskssssssssso....",
        "......ossssskkssssso....",
        "......osksssssssksso....",
        "......osssskssssssso....",
        "......osskssssksssso....",
        "......oossoooooossoo....",
        ".......osso....osso.....",
        ".......osso....osso.....",
        ".......oeeo....oeeo.....",
        ".......oooo....oooo.....",
    ];

    public static readonly string[] Zebra =
    [
        "........................",
        ".......oo......oo.......",
        "......ommo....ommo......",
        "......ommoooooommo......",
        ".....oommmoooommmoo.....",
        "....oowwwmmmmmmwwwoo....",
        "...owwowwommmmowwowwo...",
        "...owwowwwommowwwowwo...",
        "...owoowwwwwwwwwwoowo...",
        "...owwowwwwwwwwwwowwo...",
        "..owwoowwwwwwwwwwoowwo..",
        "..owwwoowwwwwwwwoowwwo..",
        "..owwoooowwwwwwoooowwo..",
        "..owwwoowwwwwwwwoowwwo..",
        "..owwwwwwwwwwwwwwwwwwo..",
        "...owwwwmmmmmmmmwwwwo...",
        "...owwwmmmmmmmmmmwwwo...",
        "....owmmmmmmmmmmmmwo....",
        "....ommmommmmmmommmo....",
        ".....ommmmmmmmmmmmo.....",
        "......oommmmmmmmoo......",
        ".......oooooooooo.......",
        "........................",
        "........................",
    ];

    public static readonly string[] Rhino =
    [
        "........................",
        "...oooo..........oooo...",
        "..ollllo........ollllo..",
        "..olllloooooooooollllo..",
        "..ollllllllllllllllllo..",
        "...ollllllllllllllllo...",
        "....ollllllllllllllo....",
        "....ollllllllllllllo....",
        "....olwwllllllllwwlo....",
        "....olwollllllllowlo....",
        "....ollllllllllllllo....",
        ".....olllllwwlllllo.....",
        ".....ollllowwollllo.....",
        ".....ollllowwollllo.....",
        "......olllowwolllo......",
        "......ommmmmmmmmmo......",
        "......ommmmmmmmmmo......",
        "......ommommmmommo......",
        "......ommmmmmmmmmo......",
        ".......ommmmmmmmo.......",
        ".......oommmmmmoo.......",
        "........oooooooo........",
        "........................",
        "........................",
    ];

    public static readonly string[] Hippo =
    [
        "........................",
        "........................",
        "....ooo..........ooo....",
        "...ovvvo........ovvvo...",
        "...ovpvoooooooooovpvo...",
        "...ovvvovvvvvvvvovvvo...",
        "....ooovvvvvvvvvvooo....",
        "...oovvvvvvvvvvvvvvoo...",
        "..ovvvwwovvvvvvowwvvvo..",
        "..ovvvwoovvvvvvoowvvvo..",
        "..ovvvvvvvvvvvvvvvvvvo..",
        "..ovvvvppppppppppvvvvo..",
        "..ovvvppppppppppppvvvo..",
        "..ovvvppoppppppoppvvvo..",
        "..ovvvppoppppppoppvvvo..",
        "...ovvppppppppppppvvo...",
        "....ovppppppppppppvo....",
        "....ovvppppppppppvvo....",
        ".....ovvvvvvvvvvvvo.....",
        "......ovvvvvvvvvvo......",
        "......ovvoooooovvo......",
        "......ovvo....ovvo......",
        "......oooo....oooo......",
        "........................",
    ];

    public static readonly string[] Gorilla =
    [
        "........................",
        "........................",
        ".....oooooooooooooo.....",
        "....oeeeeeeeeeeeeeeo....",
        "...oeeeeeeeeeeeeeeeeo...",
        "..ooeeooooooooooooeeoo..",
        ".oeeoemmmmmmmmmmmmeoeeo.",
        ".oeeoemoommmmmmoomeoeeo.",
        ".oeeoemwwmmmmmmwwmeoeeo.",
        ".oeeoemwommmmmmowmeoeeo.",
        "..ooeemmmmmmmmmmmmeeoo..",
        "...oeemmmoommoommmeeo...",
        "...oeeemmmmmmmmmmeeeo...",
        "....oeeooommmmoooeeo....",
        "....oeeeeeeeeeeeeeeo....",
        "...oeeeeeeeeeeeeeeeeo...",
        "..oeeelllllllllllleeeo..",
        ".oeeeelllllllllllleeeeo.",
        ".oeeeeeeeeeeeeeeeeeeeeo.",
        "oeeeoeeeeeeeeeeeeeeoeeeo",
        "oeeeoeeeeeeeeeeeeeeoeeeo",
        ".oeeoeeeeeeeeeeeeeeoeeo.",
        "..ooeeeeeeeeeeeeeeeeoo..",
        "....oooooooooooooooo....",
    ];

    public static readonly string[] Monkey =
    [
        "........................",
        "..oooo..........oooo....",
        ".okkkko........okkkko...",
        ".okhhko.oooooo.okhhko...",
        ".okhhkookkkkkkookhhko...",
        ".okkkkokkkkkkkkokkkko...",
        "..oooookkkkkkkkooooo....",
        "......okkwwkkwwkko......",
        "......okkwokkowkko......",
        "......okkhhhhhhkko......",
        "......okhhhoohhhko......",
        ".......ohhhhhhhho.......",
        "........oooooooo........",
        "......oookkkkkkooo......",
        ".....okkkkkkkkkkkko.....",
        "....okkkohhhhhhokkko....",
        "....okkohhhhhhhhokko....",
        "....okkohhhhhhhhokko....",
        "....okkkohhhhhhokkko....",
        ".....okkkkkkkkkkkko.....",
        "......ookkkkkkkkoo......",
        "........okkookko........",
        "........ooo..ooo........",
        "........................",
    ];

    public static readonly string[] Kangaroo =
    [
        "........................",
        ".....oo.oo..............",
        "....ohooho..............",
        "....ohooho..............",
        "....okkkko..............",
        "...okkkkkko.............",
        "...okwokkko.............",
        "..okkkkkkko.............",
        "..ookkkkkko.............",
        "....okkkko..............",
        "....okkkkoo.............",
        "...okhhhkkko............",
        "..okhhhhhkkko...........",
        "..okhhhhhhkkko..........",
        "..okhhhhhhhkkko.........",
        "..okhhhhhhhkkkko........",
        "..okkhhhhhhkkkkko.......",
        "..okkkhhhhkkkkkkko......",
        "..okkkkkkkkkkkkkkko.....",
        "..okkkkooookkkkeeeeo....",
        "..okkko...okkkoeeeeeo...",
        "..okkko...okkko.ooeeeo..",
        ".okkkko...okkko...ooooo.",
        ".oooooo...ooooo.........",
    ];

    public static readonly string[] Koala =
    [
        "..oooo............oooo..",
        ".ollllo..........ollllo.",
        "olwwwwlo........olwwwwlo",
        "olwwwwlloooooooollwwwwlo",
        "olwwwwllllllllllllwwwwlo",
        ".ollllllllllllllllllllo.",
        "..oolllllllllllllllloo..",
        "....ollllllllllllllo....",
        "....olwollllllllowlo....",
        "....ollllllllllllllo....",
        "....olllloooooollllo....",
        ".....olloooooooollo.....",
        ".....olloooooooollo.....",
        "......olloooooollo......",
        "......ollllllllllo......",
        ".....ollllllllllllo.....",
        "....olllmmmmmmmmlllo....",
        "...olllmmmmmmmmmmlllo...",
        "...ollmmmmmmmmmmmmllo...",
        "...ollmmmmmmmmmmmmllo...",
        "...olllmmmmmmmmmmlllo...",
        "....olllmmmmmmmmlllo....",
        ".....oooooooooooooo.....",
        "........................",
    ];

    public static readonly string[] Panda =
    [
        "........................",
        "....ooo..........ooo....",
        "...ommmo........ommmo...",
        "...ommmo........ommmo...",
        "....oooooooooooooooo....",
        "...oowwwwwwwwwwwwwwoo...",
        "..oowwwwwwwwwwwwwwwwoo..",
        "..owwooowwwwwwwwooowwo..",
        "..owooooowwwwwwooooowo..",
        "..owoowoowwwwwwoowoowo..",
        "..owooooowwwwwwooooowo..",
        "..owwooowwwoowwwooowwo..",
        "..owwwwwwwoooowwwwwwwo..",
        "...owwwwwwwoowwwwwwwo...",
        "....oowwwwwwwwwwwwoo....",
        "......oooooooooooo......",
        "....ooomwwwwwwwwmooo....",
        "...oommmwwwwwwwwmmmoo...",
        "...oommmwwwwwwwwmmmoo...",
        "...oommmwwwwwwwwmmmoo...",
        "....ooomwwwwwwwwmooo....",
        "...oooooowwwwwwoooooo...",
        "...oooooooooooooooooo...",
        "........................",
    ];

    public static readonly string[] Bear =
    [
        "........................",
        "...oooo..........oooo...",
        "..okkkko........okkkko..",
        "..okeeko........okeeko..",
        "..okkkkooooooooookkkko..",
        "...okkkkkkkkkkkkkkkko...",
        "..okkkkkkkkkkkkkkkkkko..",
        ".okkkkkkkkkkkkkkkkkkkko.",
        ".okkwwkkkkkkkkkkkkwwkko.",
        ".okkwokkkkkkkkkkkkowkko.",
        ".okkkkkkkkkkkkkkkkkkkko.",
        ".okkkkhhhhhhhhhhhhkkkko.",
        ".okkkhhhhhhhhhhhhhhkkko.",
        "..okkhhhoooooooohhhkko..",
        "..okkhhhhhhhhhhhhhhkko..",
        "...okkhhhhhhhhhhhhkko...",
        "....okkkkkkkkkkkkkko....",
        ".....ookhhhhhhhhkoo.....",
        "...ookkhhhhhhhhhhkkoo...",
        "..okkkhhhhhhhhhhhhkkko..",
        "..okkhhhhhhhhhhhhhhkko..",
        "..okkhhhhhhhhhhhhhhkko..",
        "...okkhhhhhhhhhhhhkko...",
        "....oooooooooooooooo....",
    ];

    public static readonly string[] Penguin =
    [
        "........................",
        ".........oooooo.........",
        ".......oouuuuuuoo.......",
        "......ouuuuuuuuuuo......",
        "......ouuuuuuuuuuo......",
        "......ouuwwoowwuuo......",
        "......ouuwwoowwuuo......",
        "......ouuwwyywwuuo......",
        ".....ouuuwwyywwuuuo.....",
        "....ouuuuwwwwwwuuuuo....",
        "...ouuuuwwwwwwwwuuuuo...",
        "..ouuuuwwwwwwwwwwuuuuo..",
        "..ouuuwwwwwwwwwwwwuuuo..",
        "..ouuuwwwwwwwwwwwwuuuo..",
        "..ouuuwwwwwwwwwwwwuuuo..",
        "..ouuuwwwwwwwwwwwwuuuo..",
        "..ouuuwwwwwwwwwwwwuuuo..",
        "..ouuuuwwwwwwwwwwuuuuo..",
        "...ouuuuwwwwwwwwuuuuo...",
        "....ouuuuwwwwwwuuuuo....",
        ".....oouuuuuuuuuuoo.....",
        "......oyyyooooyyyo......",
        ".......oooo..oooo.......",
        "........................",
    ];

    public static readonly string[] Walrus =
    [
        "........................",
        "........................",
        "....oooooooooooooooo....",
        "..ooeeeeeeeeeeeeeeeeoo..",
        ".oeeeeeeeeeeeeeeeeeeeeo.",
        ".oeeeeeeeeeeeeeeeeeeeeo.",
        ".oeewweeeeeeeeeeeewweeo.",
        ".oeewoeeeeeeeeeeeeoweeo.",
        ".oeeeeeeeeeeeeeeeeeeeeo.",
        ".oeeeekkkkkkkkkkkkeeeeo.",
        "..oeekkkkkkkkkkkkkkeeo..",
        "..oekkkkkkkkkkkkkkkkeo..",
        "..oekkkkkooooookkkkkeo..",
        "..oekkkkkkkkkkkkkkkkeo..",
        "..oekkwkkkkkkkkkkwkkeo..",
        "..oekkwkkkkkkkkkkwkkeo..",
        "...okwwkkkkkkkkkkwwko...",
        "...okwkkkkkkkkkkkkwko...",
        "...oeeeeeeeeeeeeeeeeo...",
        "..oeeeeeeeeeeeeeeeeeeo..",
        "..oeeeeeeeeeeeeeeeeeeo..",
        "...oeeeeeeeeeeeeeeeeo...",
        "....oooooooooooooooo....",
        "........................",
    ];

    public static readonly string[] Crocodile =
    [
        "........................",
        "........................",
        "........................",
        "........................",
        "..ooooooooo.............",
        ".onnnnnnnnnoo...........",
        ".ogygggggggggoooo.......",
        ".owowowowowgggnnnnoo....",
        ".ogggggggggggnnggnnngoo.",
        "..oooooooooggggggnnnnngo",
        "..........oggnnggggggngo",
        "..........oggggggggnnggo",
        "..........oonngggggggggo",
        "...........ogggggggggoo.",
        "...........ogoogggogo...",
        "..........oggo.oggoggo..",
        "..........onno.onnonno..",
        "..........oooo.ooo.ooo..",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
    ];

    public static readonly string[] Snake =
    [
        "........................",
        "..oooo..................",
        ".oggggo.................",
        ".ogwogooooooooooo.......",
        ".oggggggggggggggggo.....",
        ".oorrgnnnnnnnnnnnggo....",
        "...ooggggggggggggggo....",
        "....ogyyyyyyyyyyyggo....",
        "...oggyyyyyyyyyyyygo....",
        "...oggnnnnnnnnnnnggo....",
        "...oggggggggggggggo.....",
        "..ogggggggggggggoo......",
        "..oggnnnnnnnnnggo.......",
        "..ogyyyyyyyyyyygo.......",
        "..ogyyyyyyyyyyyggo......",
        "..oggnnnnnnnnnnggo......",
        "..oggggggggggggggo......",
        "...ogggggggggggggo......",
        "...oggnnnnnnnnnggo......",
        "....ogyyyyyyyyygo.......",
        "....oggyyyyyyyggo.......",
        ".....ogggggggggo........",
        "......ooooooooo.........",
        "........................",
    ];

    public static readonly string[] Parrot =
    [
        "........................",
        "........................",
        ".......oooooo...........",
        "......orrrrrro..........",
        ".....orrrrrrrro.........",
        "....orworrrrrro.........",
        "...oyyorrrrrrrro........",
        "...oyyyorrrrrrro........",
        "....oyorrrrrrrro........",
        ".....orrrrrrrrro........",
        ".....orrrrbbbboo........",
        ".....orrrbbbbbbo........",
        ".....orrrbbbbbbbo.......",
        ".....orrrbbbbbbbbo......",
        "......orrbbbbbbbbo......",
        "......orrrbbbbbbbo......",
        "......orrrrbbbbbbo......",
        ".......orrrrbbbbbo......",
        ".......orrrrrbbbbo......",
        "........oyyorrrro.......",
        "........oyyyooooo.......",
        ".........oyo............",
        ".........ooo............",
        "........................",
    ];

    public static readonly string[] Flamingo =
    [
        "........................",
        ".........ooooo..........",
        "........opppppo.........",
        ".......oppwopppo........",
        "......oodppppppo........",
        ".....oddooppppo.........",
        ".....ooo..oppo..........",
        "..........oppo..........",
        "..........oppo..........",
        ".........oppo...........",
        ".........oppo...........",
        "........oppo............",
        "......oooppooo..........",
        ".....oppppppppoo........",
        "....opppppppppppo.......",
        "...opddddddppppppo......",
        "...opddddddddpppppo.....",
        "...opddddddddpppppo.....",
        "....opddddddpppppo......",
        ".....ooddddppppoo.......",
        ".......ooppppoo.........",
        ".........oppo...........",
        ".........oppo...........",
        ".........oooo...........",
    ];

    public static readonly string[] Apple =
    [
        "........................",
        "..........oooo..........",
        ".......oookkkkooo.......",
        "......onnnokkonnno......",
        "......onnokkkkonno......",
        ".....oorrrrrrrrrroo.....",
        "...oorrrrrrrrrrrrrroo...",
        "..orrrrrrrrrrrrrrrrddo..",
        ".orrrrrrrrrrrrrrrrddddo.",
        ".orrwwrrrrrrrrrrrdwwddo.",
        ".orrwwrrrrrrrrrrddwwddo.",
        "orrrrrrrrrrrrrrddddddddo",
        "orrrrrrrrrrrrrdddddddddo",
        "orrrrrrrrrrrrddddddddddo",
        "orrrrrrrrrrrdddddddddddo",
        "orrrrrrrrrrddddddddddddo",
        ".orrrrrrrrddddddddddddo.",
        ".orrrrrrrdddddddddddddo.",
        "..orrrrrdddddddddddddo..",
        "...oorrddddddddddddoo...",
        ".....oooddddddddooo.....",
        ".......oooooooooo.......",
        "........................",
        "........................",
    ];

    public static readonly string[] Pear =
    [
        "........................",
        "..........oooo..........",
        ".......oookkkkooo.......",
        "......onnnokkonnno......",
        "......onnokkkkonno......",
        "........oggggggo........",
        ".......oggggggggo.......",
        "......oggggggggggo......",
        ".....ogggggggggggno.....",
        ".....ogwggggggggwno.....",
        "....oggwgggggggnwnno....",
        "....ogggggggggnnnnno....",
        "...ogggggggggnnnnnnno...",
        "..ogggggggggnnnnnnnnno..",
        "..oggggggggnnnnnnnnnno..",
        ".oggggggggnnnnnnnnnnnno.",
        ".ogggggggnnnnnnnnnnnnno.",
        ".oggggggnnnnnnnnnnnnnno.",
        "..oggggnnnnnnnnnnnnnno..",
        "..ogggnnnnnnnnnnnnnnno..",
        "...oonnnnnnnnnnnnnnoo...",
        ".....oooooooooooooo.....",
        "........................",
        "........................",
    ];

    public static readonly string[] Banana =
    [
        "........................",
        "........................",
        ".........ooo............",
        "........okkko...........",
        ".......oyyyko...........",
        "......oyyyyyo...........",
        ".....oyyssyyo...........",
        ".....oyssyyyo...........",
        "....oysssyyyo...........",
        "....oysssyyyyo..........",
        "....oyssssyyyyo.........",
        "....oyssssyyyyyo........",
        "....oysssssyyyyyo.......",
        ".....oysssssyyyyyo......",
        ".....oyysssssyyyyyo.....",
        "......oyysssssyyyyyo....",
        ".......oyyssssyyyyyyo...",
        "........oyyssssyyyyyo...",
        ".........oyyyssssyyyo...",
        "..........ooyyysssyyo...",
        "............ooyyyyyoo...",
        "..............ooooo.....",
        "........................",
        "........................",
    ];

    public static readonly string[] Orange =
    [
        "........................",
        "........................",
        "..........oooo..........",
        ".......ooonnnnooo.......",
        "......onnnonnonnno......",
        ".....ooaaaaaaaaaaoo.....",
        "....oaaaaaaaaaaaaaao....",
        "...oaaaaaaaaaaaaaaako...",
        "..oaaaaaaaaaaaaaaakkko..",
        "..oaawaaaaaaaaaaakwkko..",
        ".oaawaaaaaaaaaaakkkwkko.",
        ".oaaaaaaaaaaaaakkkkkkko.",
        ".oaaaaaaaaaaaakkkkkkkko.",
        ".oaaaaaaaaaaakkkkkkkkko.",
        ".oaaaaaaaaaakkkkkkkkkko.",
        ".oaaaaaaaaakkkkkkkkkkko.",
        "..oaaaaaaakkkkkkkkkkko..",
        "..oaaaaaakkkkkkkkkkkko..",
        "...oaaaakkkkkkkkkkkko...",
        "....oaakkkkkkkkkkkko....",
        ".....ookkkkkkkkkkoo.....",
        ".......oooooooooo.......",
        "........................",
        "........................",
    ];

    public static readonly string[] Lemon =
    [
        "........................",
        "........................",
        "..........oooo..........",
        "..........oggo..........",
        ".........oyyyyo.........",
        "......oooyyyyyyooo......",
        ".....oyyyyyyyyyyyyo.....",
        "...ooyyyyyyyyyyyyyyoo...",
        "..oyyyyyyyyyyyyyyyssso..",
        ".oyywyyyyyyyyyyyysswsso.",
        ".oyywyyyyyyyyyyyssswsso.",
        "oyyyyyyyyyyyyyysssssssso",
        "oyyyyyyyyyyyyyssssssssso",
        "oyyyyyyyyyyyysssssssssso",
        "oyyyyyyyyyyyssssssssssso",
        ".oyyyyyyyyyssssssssssso.",
        ".oyyyyyyyysssssssssssso.",
        "..oyyyyyysssssssssssso..",
        "...oyyyysssssssssssso...",
        "....ooysssssssssssoo....",
        "......oossssssssoo......",
        ".......oooooooooo.......",
        "........................",
        "........................",
    ];

    public static readonly string[] Strawberry =
    [
        "........................",
        "........................",
        "..........oooo..........",
        ".......ooonnnnooo.......",
        "......onnnnnnnnnno......",
        ".....onnnnnnnnnnnno.....",
        "....oonnnnnnnnnnnnoo....",
        "...orrrnnrrrrrrnnrrro...",
        "..orrrrrrrrrrrrrrrrrro..",
        ".orwrrrwrrrrrrrrwrrrwro.",
        ".orrrrrrrrrwwrrrrrrrrro.",
        "orwrrrwrrrrrrrrrrwrrrwro",
        "orrrrrrrrrwrrwrrrrrrrrro",
        "orwrdddwddddddddwdddrwro",
        ".odddddddwddddwdddddddo.",
        ".odwdddwddddddddwdddwdo.",
        "..odddddddwddwdddddddo..",
        "..odwdddwddddddwdddwdo..",
        "...oddddddddddddddddo...",
        "....odddwddddddwdddo....",
        ".....ooddddddddddoo.....",
        ".......oooooooooo.......",
        "........................",
        "........................",
    ];

    public static readonly string[] Grapes =
    [
        "........................",
        "............oo..........",
        "...........okko.........",
        ".......oooookkooooo.....",
        "......ovvvvoooovvvvo....",
        "......ovvvvo..ovvvvo....",
        "......ovvvvoooovvvvo....",
        "....oovvvvovvvvovvvvoo..",
        "...ovvvvvovvvvvvovvvvvo.",
        "...ovvvvovvvvvvvvovvvvo.",
        "...ovvvvovvvvvvvvovvvvo.",
        "...oooooovvvvvvvvoooooo.",
        "....ojjjooooooooojjjo...",
        "...ojjjjojjjjjjojjjjjo..",
        "...ojjjjojjjjjjojjjjjo..",
        "...oooooojjjjjjoooooo...",
        "....ojjjjoooooojjjjo....",
        "....ojjjjjooojjjjjjo....",
        ".....ojjjjjjjjjjjjo.....",
        "......ojjjjjjjjjjo......",
        ".......ojjjjjjjjo.......",
        "........oojjjjoo........",
        "..........oooo..........",
        "........................",
    ];

    public static readonly string[] Watermelon =
    [
        "........................",
        "........................",
        "........................",
        ".....oooooooooooooo.....",
        "....onnnnnnnnnnnnnno....",
        "....oggggggggggggggo....",
        "...oggggggggggggggggo...",
        "...owwwwwwwwwwwwwwwwo...",
        "..owwwwwwwwwwwwwwwwwwo..",
        "..orrrrrrrrrrrrrrrrrro..",
        "..orrrorrrrrrrrorrrrro..",
        "..orrrrrrrorrrrrrrrrro..",
        "...oddddddddddddddddo...",
        "...odddodddddoddddddo...",
        "....oddddddddddddddo....",
        "....odddddodddddoddo....",
        ".....oddddddddddddo.....",
        "......oddddodddddo......",
        ".......oddddddddo.......",
        "........oddddddo........",
        ".........ooddoo.........",
        "...........oo...........",
        "........................",
        "........................",
    ];

    public static readonly string[] Pineapple =
    [
        "........................",
        "..........oooo..........",
        ".........onggno.........",
        "......oooonggnoooo......",
        ".....onngonggnognno.....",
        "....onngoggggggognno....",
        "....onggoggggggoggno....",
        ".....ooggoggggoggoo.....",
        "......ooooyyyyoooo......",
        ".....ooyysyyyysyyoo.....",
        "....oyysyysyysyysyyo....",
        "...oysyysyyssyysyysyo...",
        "...oyysyysyyyysyysyyo...",
        "..oysyysyysyysyysyysyo..",
        "..oyysyysyyssyysyysyyo..",
        "..oysyysyysyysyysyysyo..",
        "..oyysyysyyssyysyysyyo..",
        "..oysyysyysyysyysyysyo..",
        "...oyysyysyyyysyysyyo...",
        "...oysyysyyssyysyysyo...",
        "....ooyysyyssyysyyoo....",
        "......oooooooooooo......",
        "........................",
        "........................",
    ];

    public static readonly string[] Peach =
    [
        "........................",
        "........................",
        ".......oooooooooo.......",
        "......onnnnoonnnno......",
        "......onnnoooonnno......",
        ".....ooppppppppppoo.....",
        "....oppppppppppppppo....",
        "...oppppppppppppppppo...",
        "..oppppppppppppppppddo..",
        "..oppwppppppppppppwddo..",
        ".oppwppppppppppppddwddo.",
        ".oppppppppppppppddddddo.",
        ".opppppppppppppdddddddo.",
        ".oppppppppppppddddddddo.",
        ".opppppppppppdddddddddo.",
        ".oppppppppppddddddddddo.",
        "..oppppppppddddddddddo..",
        "..opppppppdddddddddddo..",
        "...opppppdddddddddddo...",
        "....opppdddddddddddo....",
        ".....ooddddddddddoo.....",
        ".......oooooooooo.......",
        "........................",
        "........................",
    ];

    public static readonly string[] Kiwi =
    [
        "........................",
        "........................",
        "......oooooooooooo......",
        "....ookkkkkkkkkkkkoo....",
        "...okkkkkkkkkkkkkkkko...",
        "..okkggggggggggggggkko..",
        "..okggggggggggggggggko..",
        ".okggggggggggggggggggko.",
        ".okgggggwwwwwwwwgggggko.",
        ".okggggwwwwwwwwwwggggko.",
        "okggggwwwwwwwwwwwwggggko",
        "okggggwwwwwwwwwwwwggggko",
        "okggggwwwwwwwwwwwwggggko",
        "okggggwwwwwwwwwwwwggggko",
        ".okggggwwwwwwwwwwggggko.",
        ".okgggggwwwwwwwwgggggko.",
        ".okggggggggggggggggggko.",
        "..okggggggggggggggggko..",
        "..okkggggggggggggggkko..",
        "...okkkkkkkkkkkkkkkko...",
        "....ookkkkkkkkkkkkoo....",
        "......oooooooooooo......",
        "........................",
        "........................",
    ];

    public static readonly string[] Avocado =
    [
        "........................",
        "........................",
        "..........oooo..........",
        "........oonnnnoo........",
        "......oonnnnnnnnoo......",
        ".....onnggggggggnno.....",
        "....onggggggggggggno....",
        "....onggggggggggggno....",
        "...onggggggggggggggno...",
        "...onggggggggggggggno...",
        "..onggggggggggggggggno..",
        "..ongggggkkkkkkgggggno..",
        ".ongggggkkkkkkkkgggggno.",
        ".onggggkkkkkkkkkkggggno.",
        ".onggggkkkkkkkkkkggggno.",
        ".onggggkkkkkkkkkkggggno.",
        ".ongggggkkkkkkkkgggggno.",
        "..ongggggkkkkkkgggggno..",
        "..onggggggggggggggggno..",
        "...onnggggggggggggnno...",
        "....oonnnnnnnnnnnnoo....",
        "......oooooooooooo......",
        "........................",
        "........................",
    ];

    public static readonly string[] Tomato =
    [
        "........................",
        "........................",
        "..........oooo..........",
        "......oooonggnoooo......",
        ".....onggggggggggno.....",
        "....onggonggggnoggno....",
        "...oorronggggggnorroo...",
        "..orrrrrrrrrrrrrrrrddo..",
        ".orrrrrrrrrrrrrrrrddddo.",
        ".orrwwrrrrrrrrrrrdwwddo.",
        "orrwwrrrrrrrrrrrdddwwddo",
        "orrrrrrrrrrrrrrddddddddo",
        "orrrrrrrrrrrrrdddddddddo",
        "orrrrrrrrrrrrddddddddddo",
        "orrrrrrrrrrrdddddddddddo",
        ".orrrrrrrrrdddddddddddo.",
        ".orrrrrrrrddddddddddddo.",
        "..orrrrrrddddddddddddo..",
        "..orrrrrdddddddddddddo..",
        "...oorrddddddddddddoo...",
        ".....ooddddddddddoo.....",
        ".......oooooooooo.......",
        "........................",
        "........................",
    ];

    public static readonly string[] Carrot =
    [
        "........................",
        "......oo.oooooo.oo......",
        ".....onnoonnnnoonno.....",
        ".....onnonnnnnnonno.....",
        "......onnonnnnonno......",
        "......oonnnnnnnnoo......",
        "........ooaaaaoo........",
        ".......oaaaaaaaao.......",
        ".......oaaaaaaaao.......",
        "......oaakaaaakaao......",
        "......oaaaaaaaaaao......",
        "......oaaaaaaaaaao......",
        ".......oakaaaakao.......",
        ".......oaaaaaaaao.......",
        ".......oaaaaaaaao.......",
        "........oakaakao........",
        "........oaaaaaao........",
        "........oaaaaaao........",
        ".........oaaaao.........",
        ".........oaaaao.........",
        ".........oaaaao.........",
        "..........oaao..........",
        "..........oooo..........",
        "........................",
    ];

    public static readonly string[] Broccoli =
    [
        "........................",
        "......oooooooooooo......",
        "....oonnnnnnnnnnnnoo....",
        "...onnggnnggggnnggnno...",
        "..onnggnnggggggnnggnno..",
        "..onggnnggggggggnnggno..",
        ".onggnnggggggggggnnggno.",
        ".onnggggnnggggnnggggnno.",
        "onggnnggggggggggggnnggno",
        "onggggnnggggggggnnggggno",
        "onnggggggnnggnnggggggnno",
        ".onnggnnggggggggnnggnno.",
        "..oonnggggggggggggnnoo..",
        "....ooonnggggggnnooo....",
        ".......oossssssoo.......",
        ".......osssssssso.......",
        "........osssssso........",
        "........osssssso........",
        "........osssssso........",
        "........osssssso........",
        ".........osssso.........",
        ".........osssso.........",
        "..........oooo..........",
        "........................",
    ];

    public static readonly string[] Corn =
    [
        "........................",
        "..........oooo..........",
        ".......ooonggnooo.......",
        "......onnnoggonnno......",
        ".....onnggggggggnno.....",
        "....onnggyyyyyyggnno....",
        "...onggyysyyyysyyggno...",
        "...onggysyyssyysyggno...",
        "..onggyysyyssyysyyggno..",
        "..onggysyysyysyysyggno..",
        "..ongyysyysyysyysyygno..",
        "..ongysyysyyyysyysygno..",
        "..ongyysyysyysyysyygno..",
        "..ongysyysyyyysyysygno..",
        "..onggyysyyssyysyyggno..",
        "...onggysyyssyysyggno...",
        "...onggyysyyyysyyggno...",
        "....onggyysyysyyggno....",
        "....onnggyyyyyyggnno....",
        ".....oonggggggggnoo.....",
        ".......oonnggnnoo.......",
        ".........oooooo.........",
        "........................",
        "........................",
    ];

    public static readonly string[] Eggplant =
    [
        "........................",
        "..........oooo..........",
        "........oonggnoo........",
        "......oonggggggnoo......",
        ".....ongggonnogggno.....",
        ".....onggonvvnoggno.....",
        "....oovvvvvvvvvvvvoo....",
        "...ovvvvvvvvvvvvvvvjo...",
        "..ovvvvvvvvvvvvvvvjjjo..",
        "..ovvwvvvvvvvvvvvjwjjo..",
        ".ovvwvvvvvvvvvvvjjjwjjo.",
        ".ovvvvvvvvvvvvvjjjjjjjo.",
        ".ovvvvvvvvvvvvjjjjjjjjo.",
        ".ovvvvvvvvvvvjjjjjjjjjo.",
        ".ovvvvvvvvvvjjjjjjjjjjo.",
        ".ovvvvvvvvvjjjjjjjjjjjo.",
        "..ovvvvvvvjjjjjjjjjjjo..",
        "..ovvvvvvjjjjjjjjjjjjo..",
        "...ovvvvjjjjjjjjjjjjo...",
        "....ovvjjjjjjjjjjjjo....",
        ".....oojjjjjjjjjjoo.....",
        ".......oooooooooo.......",
        "........................",
        "........................",
    ];

    public static readonly string[] Pumpkin =
    [
        "........................",
        "........................",
        "..........oooo..........",
        ".........onnnno.........",
        "........onnggnno........",
        "......ooonggggnooo......",
        "....ooaaaooooooaaaoo....",
        "...oaaaaaaaaaaaaaaaao...",
        "..oaaaaaoaaaaaaoaaaaao..",
        ".oaaaaaaoaaaaaaoaaaaaao.",
        ".oaaaaaaoaaaaaaoaaaaaao.",
        "oaaaaaaaoaaaaaaoaaaaaaao",
        "oaakkaaaoaaaaaaoaaakkaao",
        "oakkkaaaoakkkkaoaaakkkao",
        "okkkkkkkokkkkkkokkkkkkko",
        ".okkkkkkokkkkkkokkkkkko.",
        ".okkkkkkokkkkkkokkkkkko.",
        "..okkkkkokkkkkkokkkkko..",
        "..okkkkkokkkkkkokkkkko..",
        "...ookkkkokkkkokkkkoo...",
        ".....ookkkokkokkkoo.....",
        ".......oooooooooo.......",
        "........................",
        "........................",
    ];

    public static readonly string[] Chilli =
    [
        "........................",
        "........................",
        "..........ooo...........",
        ".........onnno..........",
        ".........onnno..........",
        "........oonnoo..........",
        ".......onnnoo...........",
        "......oonno.............",
        ".....orrro..............",
        "....orrrro..............",
        "....orrrrro.............",
        "....orrrrrro............",
        "....ordrrrrro...........",
        "....orddrrrrro..........",
        "....ordddrrrrro.........",
        ".....oddddrrrrro........",
        ".....odddddrrrrro.......",
        "......odddddrrrro.......",
        ".......odddddrrro.......",
        "........odddddrro.......",
        ".........oodddrro.......",
        "...........ooddoo.......",
        ".............oo.........",
        "........................",
    ];

    public static readonly string[] Onion =
    [
        "........................",
        "..........oooo..........",
        "........oonggnoo........",
        ".......onggggggno.......",
        "......onggonnoggno......",
        "......ongonvvnogno......",
        ".....oovvvvvvvvvvoo.....",
        "....ovvvvvvvvvvvvvvo....",
        "...ovvvovvvvvvvvovvvo...",
        "..ovpvovvvvvvvvvvovpvo..",
        "..ovpvovvvovvovvvovpvo..",
        ".ovpvovpvovvvvovpvovpvo.",
        ".ovpvovpvovppvovpvovpvo.",
        ".ovpvovpvovppvovpvovpvo.",
        ".ovppvovpvoppovpvovppvo.",
        ".ovppvovpvoppovpvovppvo.",
        "..ovppvovpvppvpvovppvo..",
        "..ovvppvovppppvovppvvo..",
        "...ovvppvvppppvvppvvo...",
        "....ovvvvvvvvvvvvvvo....",
        ".....oovvvvvvvvvvoo.....",
        ".......oooooooooo.......",
        "........................",
        "........................",
    ];

    public static readonly string[] Car =
    [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........oooooooo........",
        ".......obbbbbbbbo.......",
        "......obccccocccco......",
        ".....obbccccoccccbo.....",
        "....obbbbbbbbbbbbbbo....",
        "...obbbbbbbbbbbbbbbbo...",
        "..obbbbbbbbbbbbbbbbbbo..",
        "..obbbbbbbbbbbbbbbbbbo..",
        "..ouuuuuuuuuuuuuuuuuuo..",
        "..ouuuuuuuuuuuuuuuuuuo..",
        "..ooooxxooooooooxxoooo..",
        "....oxxxxo....oxxxxo....",
        "....oxllxo....oxllxo....",
        "....oxxxxo....oxxxxo....",
        ".....oooo......oooo.....",
        "........................",
        "........................",
        "........................",
    ];

    public static readonly string[] Taxi =
    [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........oooooooo........",
        ".......oyyyyyyyyo.......",
        "......oyccccocccco......",
        ".....oyyccccoccccyo.....",
        "....oyyyyyyyyyyyyyyo....",
        "...oyyyyyyyyyyyyyyyyo...",
        "..oyyyyyyyyyyyyyyyyyyo..",
        "..oyyyyyyyyyyyyyyyyyyo..",
        "..oxxxxxxxxxxxxxxxxxxo..",
        "..oxxxxxxxxxxxxxxxxxxo..",
        "..ooooxxooooooooxxoooo..",
        "....oxxxxo....oxxxxo....",
        "....oxllxo....oxllxo....",
        "....oxxxxo....oxxxxo....",
        ".....oooo......oooo.....",
        "........................",
        "........................",
        "........................",
    ];

    public static readonly string[] Bus =
    [
        "........................",
        "........................",
        "...oooooooooooooooooo...",
        "..oaaaaaaaaaaaaaaaaaao..",
        "..oaccoccoccoccoccoccao.",
        "..oaccoccoccoccoccoccao.",
        "..oaaaaaaaaaaaaaaaaaaao.",
        "..oaaaaaaaaaaaaaaaaaaao.",
        "..oaccoccoccoccoccoccao.",
        "..oaccoccoccoccoccoccao.",
        "..oaaaaaaaaaaaaaaaaaaao.",
        "..okkkkkkkkkkkkkkkkkkko.",
        "..okkkkkkkkkkkkkkkkkkko.",
        "..okkkkkkkkkkkkkkkkkkko.",
        "..okkkkkkkkkkkkkkkkkkko.",
        "..oooxxooooooooooxxoooo.",
        "....oxxxxo......oxxxxo..",
        "....oxllxo......oxllxo..",
        "....oxxxxo......oxxxxo..",
        ".....oooo........oooo...",
        "........................",
        "........................",
        "........................",
        "........................",
    ];

    public static readonly string[] Truck =
    [
        "........................",
        "........................",
        "........................",
        ".........ooooooooooooo..",
        "........olllllllllllllo.",
        "........olllllllllllllo.",
        "...oooooolllllllllllllo.",
        "..obbbbbolllllllllllllo.",
        "..obcccbolllllllllllllo.",
        "..obcccbolllllllllllllo.",
        "..obbbbbolllllllllllllo.",
        ".obbbbbbolllllllllllllo.",
        ".obbbbbbommmmmmmmmmmmmo.",
        ".ouuuuuuommmmmmmmmmmmmo.",
        ".ouuuuuuommmmmmmmmmmmmo.",
        ".ooxxooooooxxoooooxxooo.",
        "..oxxxxo..oxxxxo.oxxxxo.",
        "..oxllxo..oxllxo.oxllxo.",
        "..oxxxxo..oxxxxo.oxxxxo.",
        "...oooo....oooo...oooo..",
        "........................",
        "........................",
        "........................",
        "........................",
    ];

    public static readonly string[] Train =
    [
        "........................",
        "........................",
        "......oooo..............",
        "......oxxo..............",
        "......oxxooooooooooo....",
        ".....oooouuuuuuuuuuuo...",
        "....ouuuuuuuuuuuuuuuo...",
        "....ouuuuuuuuuuuuuuuo...",
        "....ouccoccouuoccocco...",
        "....ouccoccouuoccocco...",
        "....ouuuuuuuuuuuuuuuo...",
        "...ouuuuuuuuuuuuuuuuuo..",
        "...orrrrrrrrrrrrrrrrro..",
        "...orrrrrrrrrrrrrrrrro..",
        "...ooxxoooxxoooxxooxxoo.",
        "...oxxxxooxxxxooxxxxxo..",
        "...oxllxooxllxooxlllxo..",
        "...oxxxxooxxxxooxxxxxo..",
        "....oooo..oooo..ooooo...",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
    ];

    public static readonly string[] Tram =
    [
        "........................",
        "..........oo............",
        "..........oo............",
        "....oooooooooooooooo....",
        "...oggggggggggggggggo...",
        "...ogcccocccocccoccgo...",
        "...ogcccocccocccoccgo...",
        "...ogcccocccocccoccgo...",
        "...oggggggggggggggggo...",
        "...oggggggggggggggggo...",
        "...onnnnnnnnnnnnnnnno...",
        "...onnnoccconnnocccno...",
        "...onnnoccconnnocccno...",
        "...onnnnnnnnnnnnnnnno...",
        "...oyyyyyyyyyyyyyyyyo...",
        "...ooxxooooooooooxxooo..",
        "....oxxxxo.....oxxxxo...",
        "....oxllxo.....oxllxo...",
        "....oxxxxo.....oxxxxo...",
        ".....oooo.......oooo....",
        "........................",
        "........................",
        "........................",
        "........................",
    ];

    public static readonly string[] FireEngine =
    [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........oooooooo........",
        ".......orrrrrrrro.......",
        "......orccccocccco......",
        ".....orrccccoccccro.....",
        "....orrrrrrrrrrrrrro....",
        "...orrrrrrrrrrrrrrrro...",
        "..orrrrrrrrrrrrrrrrrro..",
        "..orrrrrrrrrrrrrrrrrro..",
        "..oddddddddddddddddddo..",
        "..oddddddddddddddddddo..",
        "..ooooxxooooooooxxoooo..",
        "....oxxxxo....oxxxxo....",
        "....oxllxo....oxllxo....",
        "....oxxxxo....oxxxxo....",
        ".....oooo......oooo.....",
        "........................",
        "........................",
        "........................",
    ];

    public static readonly string[] Ambulance =
    [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        "........oooooooo........",
        ".......owwwwwwwwo.......",
        "......owccccocccco......",
        ".....owwccccoccccwo.....",
        "....owwwwwwwwwwwwwwo....",
        "...owwwwwwrrwwwwwwwwo...",
        "..owwwwwwrrrrwwwwwwwwo..",
        "..owwwwwwrrrrwwwwwwwwo..",
        "..orrrrrrrrrrrrrrrrrro..",
        "..orrrrrrrrrrrrrrrrrro..",
        "..ooooxxooooooooxxoooo..",
        "....oxxxxo....oxxxxo....",
        "....oxllxo....oxllxo....",
        "....oxxxxo....oxxxxo....",
        ".....oooo......oooo.....",
        "........................",
        "........................",
        "........................",
    ];

    public static readonly string[] PoliceCar =
    [
        "........................",
        "........................",
        "........................",
        "........................",
        ".........oooooo.........",
        ".........obbrro.........",
        "........oooooooo........",
        ".......owwwwwwwwo.......",
        "......owccccocccco......",
        ".....owwccccoccccwo.....",
        "....owwwwwwwwwwwwwwo....",
        "...owwwwwwwwwwwwwwwwo...",
        "..owwwwwwwwwwwwwwwwwwo..",
        "..owwwwwwwwwwwwwwwwwwo..",
        "..ouuuuuuuuuuuuuuuuuuo..",
        "..ouuuuuuuuuuuuuuuuuuo..",
        "..ooooxxooooooooxxoooo..",
        "....oxxxxo....oxxxxo....",
        "....oxllxo....oxllxo....",
        "....oxxxxo....oxxxxo....",
        ".....oooo......oooo.....",
        "........................",
        "........................",
        "........................",
    ];

    public static readonly string[] Bicycle =
    [
        "........................",
        "........................",
        "........................",
        "........................",
        ".............ooooooo....",
        "............ollllllro...",
        "......ooooo.olllllllo...",
        ".....oxxxxxo.ooolooo....",
        ".....oxxxxxo...olo......",
        "...oooooloooooooloooo...",
        "..oxxxxxlllllllllxxxxo..",
        ".oxxxxxxlooooooxlxxxxxo.",
        "oxxxoooxlxo.ooxlllooxxxo",
        "xxxo.o.olxxolllxlooooxxx",
        "xxo.oloolllloxxollllooxx",
        "xxo.ollllxxooxxollllooxx",
        "xxo.oloooxxooxxoolllooxx",
        "xxxo.o.oxxxooxxxoooooxxx",
        "oxxxoooxxxo..oxxxoooxxxo",
        ".oxxxxxxxo....oxxxxxxxo.",
        "..oxxxxxo......oxxxxxo..",
        "...ooooo........ooooo...",
        "........................",
        "........................",
    ];

    public static readonly string[] Motorbike =
    [
        "........................",
        "........................",
        "........................",
        "........................",
        "........................",
        ".............ooooooo....",
        "............oxxxxxxxo...",
        ".............oorrrro....",
        "........ooooooorllro....",
        ".......oxxxxrrrrllo.....",
        ".......oxxxxrrrrllo.....",
        "...ooooorrrrrrrrllooo...",
        "..oxxxrrrrrrrrrrllxxxo..",
        ".oxxxxrrrrrrrrrrrrxxxxo.",
        "oxxxoorrrrrrrrrrrrooxxxo",
        "oxxo.oxxxxrrrrrrrro.oxxo",
        "oxxoolxxxxooooxxoolooxxo",
        "oxxo.oooxxo..oxxo.o.oxxo",
        "oxxxoooxxxo..oxxxoooxxxo",
        ".oxxxxxxxo....oxxxxxxxo.",
        "..oxxxxxo......oxxxxxo..",
        "...ooooo........ooooo...",
        "........................",
        "........................",
    ];

    public static readonly string[] TrafficLight =
    [
        "........................",
        "......oooooooooooo......",
        ".....oxxxxxxxxxxxxo.....",
        "....oxxxxxxxxxxxxxxo....",
        "....oxxooooooooooxxo....",
        "....oxorrrrrrrrrroxo....",
        "....oxorrrrrrrrrroxo....",
        "....oxorrrrrrrrrroxo....",
        "....oxooooooooooooxo....",
        "....oxoyyyyyyyyyyoxo....",
        "....oxoyyyyyyyyyyoxo....",
        "....oxoyyyyyyyyyyoxo....",
        "....oxooooooooooooxo....",
        "....oxoggggggggggoxo....",
        "....oxoggggggggggoxo....",
        "....oxoggggggggggoxo....",
        "....oxxooooooooooxxo....",
        "....oxxxxxxxxxxxxxxo....",
        ".....oxxxxxxxxxxxxo.....",
        "......ooommmmmmooo......",
        ".......ommmmmmmmo.......",
        ".......ommmmmmmmo.......",
        "......ommmmmmmmmmo......",
        "......oooooooooooo......",
    ];

    public static readonly string[] NoEntry =
    [
        "........................",
        "........................",
        "........oooooooo........",
        "......oorrrrrrrroo......",
        ".....orrrrrrrrrrrro.....",
        "....orrrrrrrrrrrrrro....",
        "...orrrrrrrrrrrrrrrro...",
        "..orrrrrrrrrrrrrrrrrro..",
        "..orwwwwwwwwwwwwwwwwro..",
        "..orwwwwwwwwwwwwwwwwro..",
        "..owwwwwwwwwwwwwwwwwwo..",
        "..owwwwwwwwwwwwwwwwwwo..",
        "..orwwwwwwwwwwwwwwwwro..",
        "..orwwwwwwwwwwwwwwwwro..",
        "..orrrrrrrrrrrrrrrrrro..",
        "..orrrrrrrrrrrrrrrrrro..",
        "...orrrrrrrrrrrrrrrro...",
        "....orrrrrrrrrrrrrro....",
        ".....orrrrrrrrrrrro.....",
        "......ooommmmmmooo......",
        ".........ommmmo.........",
        ".........ommmmo.........",
        ".........ommmmo.........",
        ".........oooooo.........",
    ];

    public static readonly string[] Cone =
    [
        "........................",
        "........................",
        "..........oooo..........",
        ".........oaaaao.........",
        ".........oaaaao.........",
        "........oaaaaaao........",
        "........oaaaaaao........",
        ".......owwwwwwwwo.......",
        ".......owwwwwwwwo.......",
        "......oaaaaaaaaaao......",
        "......oaaaaaaaaaao......",
        ".....oaaaaaaaaaaaao.....",
        ".....owwwwwwwwwwwwo.....",
        "....owwwwwwwwwwwwwwo....",
        "....oaaaaaaaaaaaaaao....",
        "...oaaaaaaaaaaaaaaaao...",
        "...oaaaaaaaaaaaaaaaao...",
        "..oaaaaaaaaaaaaaaaaaao..",
        "..owwwwwwwwwwwwwwwwwwo..",
        ".owwwwwwwwwwwwwwwwwwwwo.",
        ".oxxxxxxxxxxxxxxxxxxxxo.",
        ".oxxxxxxxxxxxxxxxxxxxxo.",
        ".oooooooooooooooooooooo.",
        "........................",
    ];

    public static readonly string[] StreetLamp =
    [
        "........................",
        "........................",
        "........................",
        "...........ooooooooo....",
        "..........oxxxmmmmmmo...",
        "..........oxxxmmmmmmoo..",
        "..........ommmmmxxxxxxo.",
        "..........ooooooxxxxxxo.",
        ".........ommmmo.oyyyyo..",
        ".........ommmmo.oyyyyo..",
        ".........ommmmo..oyyo...",
        ".........ommmmo..oyyo...",
        ".........ommmmo...oo....",
        ".........ommmmo.........",
        ".........ommmmo.........",
        ".........ommmmo.........",
        ".........ommmmo.........",
        ".........ommmmo.........",
        ".........ommmmo.........",
        ".........ommmmo.........",
        ".......ooommmmooo.......",
        "......ommmmmmmmmmo......",
        "......ommmmmmmmmmo......",
        ".......oooooooooo.......",
    ];

    public static readonly string[] Hydrant =
    [
        "...........o............",
        "..........oroo..........",
        ".........orrrro.........",
        "........orrrrro.........",
        "........orrrrroo........",
        ".......orrrrrrrro.......",
        ".......orrrrrrrro.......",
        ".......oddddddddo.......",
        ".....oooddddddddooo.....",
        "....olllrrrrrrrrlllo....",
        "....olllrrrrrrrrlllo....",
        "....olllrrrrrrrrlllo....",
        "....olllrrrrrrrrlllo....",
        ".....ooorrrrrrrrooo.....",
        ".......oddddddddo.......",
        ".......oddddddddo.......",
        ".......orrrrrrrro.......",
        ".......orrrrrrrro.......",
        ".......orrrrrrrro.......",
        "......oorrrrrrrroo......",
        ".....ollllllllllllo.....",
        ".....ollllllllllllo.....",
        ".....ollllllllllllo.....",
        "......oooooooooooo......",
    ];

    public static readonly string[] Digger =
    [
        "........................",
        "........................",
        "...............ooo......",
        "..............oyyo......",
        ".....ooooo...oyyo.......",
        "....oyyyyyo.oyyo........",
        "....oycccyooyyo.........",
        "....oycccyoyyo..........",
        "....oyyyyyoyo...........",
        "...oyyyyyyyo............",
        "...oyyyyyyyoooo.........",
        "...oyyyyyyyyyyyo........",
        "..oyyyyyyyyyyyyyo.......",
        "..oaaaaaaaaaaaaao..ooo..",
        "..oaaaaaaaaaaaaaooolllo.",
        "..ooooooooooooooolllllo.",
        "..oxxxxxxxxxxxxxollllo..",
        ".oxxooxxooxxooxxxooooo..",
        ".oxxxxxxxxxxxxxxxo......",
        ".ooxxooxxooxxooxxo......",
        "..ooooooooooooooo.......",
        "........................",
        "........................",
        "........................",
    ];

    public static readonly string[] Crane =
    [
        "........................",
        "........................",
        "........................",
        "..oooooooooooooooooooo..",
        ".oyyyyyyyyyyyyyyyyyyyyo.",
        ".oyyooyyooyyyyyooyyooyo.",
        ".oyyyyyyyyyyyyyyyyyyyyo.",
        "..ooolloooyooyooooxxxxo.",
        "....ollo.oyyyyo..oxxxxo.",
        "....ollo.oyooyo..oxxxxo.",
        "....ollo.oyyyyo...oooo..",
        "....ollo.oyooyo.........",
        "...ollllooyyyyo.........",
        "...ollllooyooyo.........",
        "...ollllooyyyyo.........",
        "...ollllooyooyo.........",
        "....oooo.oyyyyo.........",
        ".........oyooyo.........",
        ".........oyyyyo.........",
        ".......oooyooyooo.......",
        "......oxxxxxxxxxxo......",
        "......oxxxxxxxxxxo......",
        "......oxxxxxxxxxxo......",
        ".......oooooooooo.......",
    ];

    public static readonly string[] Skyscraper =
    [
        "........................",
        "..........oooo..........",
        "..........ollo..........",
        ".......oooolloooo.......",
        ".......ommmllmmmo.......",
        ".......ommmllmmmo.......",
        "....oooommmllmmmoooo....",
        "....omccomccccmoccmo....",
        "....omccomccccmoccmo....",
        "....ommmommmmmmommmo....",
        "....omccomccccmoccmo....",
        "....omccomccccmoccmo....",
        "....ommmommmmmmommmo....",
        "....omccomccccmoccmo....",
        "....omccomccccmoccmo....",
        "....ommmommmmmmommmo....",
        "....omccomccccmoccmo....",
        "....omccomccccmoccmo....",
        "....ommmommmmmmommmo....",
        "....olccolcccclocclo....",
        "....olccolcccclocclo....",
        "....olllollllllolllo....",
        "....olllollllllolllo....",
        "....oooooooooooooooo....",
    ];

    public static readonly string[] FuelPump =
    [
        "........................",
        "........................",
        "......oooooooooooo......",
        ".....orrrrrrrrrrrro.....",
        ".....orrrrrrrrrrrro.....",
        ".....orooooooooooro.....",
        ".....orowwwwwwwworo.....",
        ".....orowwwwwwwworo.....",
        ".....orooooooooooro.....",
        ".....orrrrrrrrrrrro.....",
        "ooo..orrrrrrrrrrrro..ooo",
        "oxo..orrrrrrrrrrrro..oxo",
        "oxoooorrrrrrrrrrrrooooxo",
        "oxxxxorddddddddddroxxxxo",
        "ooooxorddddddddddroxoooo",
        "....xorddddddddddrox....",
        "....xorddddddddddrox....",
        "....xorddddddddddrox....",
        "....oorddddddddddroo....",
        "......oddddddddddo......",
        "......oddddddddddo......",
        "......ollllllllllo......",
        "......ollllllllllo......",
        "......oooooooooooo......",
    ];

    public static readonly string[] Slime =
    [
        "........................",
        "........................",
        "........................",
        "..........oooo..........",
        ".......oooiiiiooo.......",
        ".....ooiiiiiiiiiioo.....",
        "....oiiiiiiiiiiiiiio....",
        "...oiiiiiiiiiiiiiiiio...",
        "..oiiiiiiiiiiiiiiiiggo..",
        "..oiiiiiiiiiiiiiiigggo..",
        ".oiiiiiiiiiiiiiiigggggo.",
        ".oiiooiiiiiiiiiiggooggo.",
        ".oiiooiiiiiiiiigggooggo.",
        ".oiiiiiiiiiiiiggggggggo.",
        ".oiiiiiiooooooooggggggo.",
        "oiiiiiiiiiiigggggggggggo",
        "oiiiiiiiiiiggggggggggggo",
        "oggggggggggggggggggggggo",
        "oggggggggggggggggggggggo",
        "oggggggggggggggggggggggo",
        ".oggggggggggggggggggggo.",
        ".oooooooooooooooooooooo.",
        "........................",
        "........................",
    ];

    public static readonly string[] Chick =
    [
        "........................",
        "........................",
        "..........oooo..........",
        ".......oooyyyyooo.......",
        "......oyyyyyyyyyyo......",
        ".....oyyyyyyyyyyyyo.....",
        "....oyyyyyyyyyyyyyyo....",
        "....oyyyyyyyyyyyyyyo....",
        "...oyyooyyyyyyyyooyso...",
        "...oyyooyyyyyyyyoosso...",
        "...oyyyyyyyyyyyyyssso...",
        "...oyyyyyoaaaaoysssso...",
        "....oyyyyoaaaaosssso....",
        "....oyyyyyyyyyssssso....",
        "...oyssyyyyyyssssssso...",
        "..oysssyyyyyssssssssso..",
        "..oysssyyyysssssssssso..",
        "..oyssyyyyssssssssssso..",
        "..oyyyyyysssssssssssso..",
        "...oyyyysssssssssssso...",
        "....oooaaooooooaaooo....",
        "......oaaoaaaaoaao......",
        "......oooooooooooo......",
        "........................",
    ];

    public static readonly string[] Kitten =
    [
        "........................",
        "...oo..............oo...",
        "..ollo............ollo..",
        "..olplo..........olplo..",
        "..olplloooooooooollplo..",
        "..ollllllllllllllllllo..",
        ".olllllllllllllllllllmo.",
        ".ollllllllllllllllllmmo.",
        ".ollwwllllllllllllwwmmo.",
        ".ollwollllllllllllowmmo.",
        ".olllllllllllllllmmmmmo.",
        ".ollllllloppppolmmmmmmo.",
        ".olllllloppppppommmmmmo.",
        "..olllllowwwwwwommmmmo..",
        "..ollllllwwwwwwmmmmmmo..",
        "...ollllllllmmmmmmmmo...",
        "....ollllllmmmmmmmmo....",
        "....olllllmmmmmmmmmo....",
        "...olllllmmmmmmmmmmmo...",
        "..olllllmmmmmmmmmmmmmo..",
        "..ollllmmmmmmmmmmmmmmo..",
        "..ommoommoommoommoommo..",
        "..oooo.oooooooooo.oooo..",
        "........................",
    ];

    public static readonly string[] Bunny =
    [
        "........................",
        "....oo............oo....",
        "...owpo..........opwo...",
        "...owpo..........opwo...",
        "...owpo.oo....oo.opwo...",
        "...owpoowpo..opwoopwo...",
        "...owwoowpo..opwoowwo...",
        "....owwowwo..owwowwo....",
        "....owwwwwo..owwwwwo....",
        "...owwwwwwwwwwwwwwllo...",
        "..owwwwwwwwwwwwwwllllo..",
        "..owwoowwwwwwwwwloollo..",
        "..owwoowwwwwwwwlloollo..",
        "..owwwwwwwoppolllllllo..",
        "..owwwwwwoppppollllllo..",
        "...owwwwwowwllolllllo...",
        "....owwwwwwllllllllo....",
        "...owwwwwwllllllllllo...",
        "..owwwwwwllllllllllllo..",
        "..owwwwwlllllllllllllo..",
        "..owwwwllllllllllllllo..",
        "...owwllllllllllllllo...",
        "....oooooooooooooooo....",
        "........................",
    ];

    public static readonly string[] Fox =
    [
        "........................",
        "..oo................oo..",
        ".oaao..............oaao.",
        ".oakao............oakao.",
        ".oaaaaooooooooooooaaaao.",
        "..oaaaaaaaaaaaaaaaaaao..",
        "..oaaaaaaaaaaaaaaaaaao..",
        ".oaaaaaaaaaaaaaaaaaaaao.",
        ".oaaooaaaaaaaaaaaaooako.",
        ".oaaooaaaaaaaaaaaaookko.",
        ".oaaaaaaaaaaaaaaaaakkko.",
        "..oaaaaaaaaaaaaaaakkko..",
        "..oaaaaaawwwwwwaakkkko..",
        "...oaaaawwwwwwwwkkkko...",
        "...oaaaawwoooowwkkkko...",
        "....oaaawwwwwwwwkkko....",
        "....oaaaawwwwwwkkkko....",
        "...oaaaaaaaakkkkkkkko...",
        "..oaaaaaaaakkkkkkkkkko..",
        "..oaaaaaaakkkkkkkkkkko..",
        "..oaawwwwwwwwwwwwwwkko..",
        "...oaawwwwwwwwwwwwkko...",
        "...oooooooooooooooooo...",
        "........................",
    ];

    public static readonly string[] Dragon =
    [
        "........................",
        ".....oo...oooo...oo.....",
        "....oyyo.oyyyyo.oyyo....",
        "....oyyooyyyyyyooyyo....",
        ".....ooggggggggggoo.....",
        "...ooggggggggggggggoo...",
        "..oggggggggggggggggggo..",
        "..ogggggggggggggggggno..",
        ".oggooggggggggggggoonno.",
        ".oggooggggggggggggoonno.",
        ".ogggggggggggggggnnnnno.",
        ".ogggggggoooooognnnnnno.",
        "..oggggggggggggnnnnnno..",
        "..ogggggggggggnnnnnnno..",
        "ooggggggyyyyyyyynnnnnnoo",
        "onngggggyyyyyyyynnnnnnno",
        "onnnggggyyyyyyyynnnnnnno",
        "onnnngggyyyyyyyynnnnnnno",
        "oonnnggggyyyyyynnnnnnnoo",
        "..oongggnnyyyynnnnnnoo..",
        "....oggnnnnnnnnnnnno....",
        "....ognoonnnnnnoonno....",
        "....ooo..oooooo..ooo....",
        "........................",
    ];

    public static readonly string[] Ghost =
    [
        "........................",
        "........................",
        "..........oooo..........",
        ".......ooowwwwooo.......",
        ".....oowwwwwwwwwwoo.....",
        "....owwwwwwwwwwwwwwo....",
        "...owwwwwwwwwwwwwwwwo...",
        "..owwwwwwwwwwwwwwwwwco..",
        "..owwwwwwwwwwwwwwwwcco..",
        ".owwoowwwwwwwwwwwwoocco.",
        ".owwoowwwwwwwwwwwcoocco.",
        ".owwwwwwwwwwwwwwcccccco.",
        ".owwwwwwoowwwwoocccccco.",
        ".owwwwwwoowwwwoocccccco.",
        ".owwwwwwwwwwwccccccccco.",
        "owwwwwwwwwwwccccccccccco",
        "owccwwwwwwwcccccccccccco",
        "owccwwwwwwccccccccccccco",
        "owccwwwwwcccccccccccccco",
        "owccwwwwccccccccccccccco",
        "owccoowccooccoocccooccco",
        "oooo..ooo..oo..ooo..oooo",
        "........................",
        "........................",
    ];

    public static readonly string[] Star =
    [
        "........................",
        "..........oooo..........",
        ".........oyyyyo.........",
        ".........oyyyyo.........",
        "........oyyyyyyo........",
        "........oyyyyyyo........",
        ".......oyyyyyyyyo.......",
        "oooooooyyyyyyyyyyooooooo",
        "oyyyyyyyyyyyyyyyyyyyyyyo",
        ".oyyyyyyyyyyyyyyyyyyyyo.",
        "..oyyyyyyyyyyyyyyyyyyo..",
        "...oyyooyyyyyyyyooyyo...",
        "...oyyooyyyyyyyyooyyo...",
        "...oyyyyyyyyyyyyyyyyo...",
        "...oyssyooyyyyooyssyo...",
        "...oyssyyyyyyyyyyssyo...",
        "....osssyyyyyyyyssso....",
        "....osssssssssssssso....",
        "...osssssssssssssssso...",
        "..ossssossssssssosssso..",
        ".osssooossssssssooossso.",
        "ossoo...oossssoo...oosso",
        "ooo.......oooo.......ooo",
        "........................",
    ];

    public static readonly string[] Cloud =
    [
        "........................",
        "........................",
        "........................",
        "........oooooooo........",
        ".......owwwwwwwwo.......",
        "....ooowwwwwwwwwwooo....",
        "...owwwwwwwwwwwwwwwco...",
        "..owwwwwwwwwwwwwwwccco..",
        "..owwwwwwwwwwwwwwcccco..",
        ".owwwwwwwwwwwwwwcccccco.",
        ".owwoowwwwwwwwwcccoocco.",
        ".owwoowwwwwwwwccccoocco.",
        ".owwwwwwwwwwwccccccccco.",
        ".owwppwwoowwccooccppcco.",
        ".owwppwwoowcccooccppcco.",
        "owwwwwwwwwccccccccccccco",
        "owwwwwwwwcccccccccccccco",
        "occcccccccccccccccccccco",
        "occcccccccccccccccccccco",
        ".occcccccccccccccccccco.",
        "..ooccccccccccccccccoo..",
        "....oooooooooooooooo....",
        "........................",
        "........................",
    ];

    public static readonly string[] Axolotl =
    [
        "........................",
        "........................",
        "..oo................oo..",
        ".oddo...oooooooo...oddo.",
        ".odddoooppppppppooodddo.",
        "..odddppppppppppppdddo..",
        "oodddppppppppppppppdddoo",
        "odddppppppppppppppppdddo",
        "oodddppppppppppppppdddoo",
        "..odddppppppppppppdddo..",
        ".odddoooppppppppooodddo.",
        ".oddo..oppppppppo..oddo.",
        "..oo...opppppppdo...oo..",
        ".......oppooooddo.......",
        "......oppppppddddo......",
        "......opppppdddddo......",
        ".....opppppdddddddo.....",
        ".....oppppddddddddo.....",
        ".....opppdddddddddo.....",
        "......opdddddddddo......",
        "......oddddddddddo......",
        ".......ooddddddoo.......",
        ".........oooooo.........",
        "........................",
    ];

    public static readonly string[] Jellyfish =
    [
        "........................",
        "........................",
        "..........oooo..........",
        ".......oooccccooo.......",
        ".....ooccccccccccoo.....",
        "....occcccccccccccco....",
        "...occcccccccccccccbo...",
        "..occcccccccccccccbbbo..",
        "..occccccccccccccbbbbo..",
        ".occccccccccccccbbbbbbo.",
        ".occoocccccccccbbboobbo.",
        ".occooccccccccbbbboobbo.",
        ".occcccccccccbbbbbbbbbo.",
        ".occccccooccbboobbbbbbo.",
        "occccccccccbbbbbbbbbbbbo",
        "obbbbbbbbbbbbbbbbbbbbbbo",
        "oobboobboobbbboobboobboo",
        ".obbo.obbo.oo.obbo.obbo.",
        ".obbo.obbo.oo.obbo.obbo.",
        "..obbo.obbo..obbo.obbo..",
        "..obbo.obbo..obbo.obbo..",
        "...obo..obo..obo..obo...",
        "...ooo..ooo..ooo..ooo...",
        "........................",
    ];

    public static readonly string[] Owlet =
    [
        "........................",
        "...oo..............oo...",
        "..okko............okko..",
        "..okkkooooooooooookkko..",
        "..okkkkkkkkkkkkkkkkkko..",
        ".okkkkkkkkkkkkkkkkkkkko.",
        ".okhhhhohhhhhhhhohhhhko.",
        "okhhhhhohhhhhhhhohhhhhko",
        "okhoohhohhoooohhohhoohko",
        "okhoohhohhoooohhohhoohko",
        "okhhhhhohhhhhhhhohhhhhko",
        "okhhhhhoyyyyyyyyohhhhhko",
        "okkhhhhhoyyyyyyohhhhhkko",
        "okkkhhhhhhhhhhhhhhhhkkko",
        ".okkkkkkkkkkkkkkkkkkkko.",
        ".okkkhhhhkkkkkkhhhhkkko.",
        ".okkhhhhhhkkkkhhhhhhkko.",
        ".okkkhhhhkkkkkkhhhhkkko.",
        "..okkkkkkkkkkkkkkkkkko..",
        "..okkkkkkkkkkkkkkkkkko..",
        "...okkkkkkkkkkkkkkkko...",
        "....oooyyooooooyyooo....",
        "......oyyoyyyyoyyo......",
        "......oooooooooooo......",
    ];

    public static readonly string[] Hedgehog =
    [
        "........................",
        "..........oooo..........",
        "........ooeeeeoo........",
        "......ooeeoeeoeeoo......",
        ".....oeeoeeeeeeoeeo.....",
        "....oeeeeoeeeeoeeeeo....",
        "...oeeoeeeeeeeeeeoeeo...",
        "..oeeeeeoeeeeeeoeeeeeo..",
        "..oeoeeeeeeeeeeeeeeoeo..",
        ".oeeeeeoeeeeeeeeoeeeeeo.",
        ".oeeeeeeeeoeeoeeeeeeexo.",
        "oeeoeeeeeeeeeeeeeeeeoxxo",
        "oeeeeeeoeeeeeeeeoeexxxxo",
        "oeeeeeeeeeeeeeeeeexxxxxo",
        "oeeeeeeeeeeeeeeeexxxxxxo",
        ".oeeeeeeeeeeeeeexxxxxxo.",
        ".oeehhhhhhhhhhhhhhhhxxo.",
        "..oehhhhhhhhhhhhhhhhxo..",
        "..ohhhoohhhhhhhhoohhho..",
        "..ohhhoohhhhhhhhoohhho..",
        "...ohhhhhhhhhhhhhhhho...",
        "...ohhhhhhoooohhhhhho...",
        "....oohhhhoooohhhhoo....",
        "......oooooooooooo......",
    ];

    public static readonly string[] Unicorn =
    [
        "........................",
        "...........oo...........",
        "..........oyyo..........",
        "..........oyyo..........",
        ".........oyyyyo.........",
        ".........oyyyyo.........",
        "......oooooooooooo......",
        "....oowwwwwwwwwwwwoo....",
        "...owwwwwwwwwwwwwwwwo...",
        "..owpwwwwwwwwwwwwwwplo..",
        ".owppwwwwwwwwwwwwwwpplo.",
        ".owppwwoowwwwwwoowlpplo.",
        ".owppwwoowwwwwwoollpplo.",
        ".owppwwwwwwwwwwwlllpplo.",
        ".owppwwwwwwwwwwllllpplo.",
        "..owpwwwwwwwwwlllllplo..",
        "..owwwwwwwwwwllllllllo..",
        "..owwwwwwwoppolllllllo..",
        "..owwwwwwwwllllllllllo..",
        "...owwwwwwllllllllllo...",
        "...owwwwwlllllllllllo...",
        "....owwwlllllllllllo....",
        "....oooooooooooooooo....",
        "........................",
    ];

    public static readonly string[] Sheep =
    [
        "........................",
        "........................",
        ".....oooooooooooooo.....",
        "...oowwwwwwwwwwwwwwoo...",
        "..owwwwwwwwwwwwwwwwwwo..",
        ".owwwwwwwwwwwwwwwwwwwwo.",
        ".owwoooooooooooooooowwo.",
        "owwoxxxxxxxxxxxxxxxxowwo",
        "owwoxxxxxxxxxxxxxxxxowwo",
        "owwoxwwxxxxxxxxxxwwxowwo",
        "owwoxwoxxxxxxxxxxowxowwo",
        "owwoxxxxxxxxxxxxxxxxowwo",
        "owwwoxxxxxxxxxxxxxxowwwo",
        ".owwwooxxxxxxxxxxoowwwo.",
        ".owwwwwoooooooooowwwwwo.",
        "owwwwwwwwwwwwwwwwwwwwwwo",
        "owwwwwwwwwwwwwwwwwwwwwwo",
        "owwwwwwwwwwwwwwwwwwwwwwo",
        ".owwwwwwwwwwwwwwwwwwwwo.",
        "..owwwwwwwwwwwwwwwwwwo..",
        "...oowwwwwwwwwwwwwwoo...",
        ".....oxxooxxxxooxxo.....",
        ".....oxxo.oxxo.oxxo.....",
        ".....oooo.oooo.oooo.....",
    ];

    public static readonly string[] Frog =
    [
        "........................",
        "........................",
        "......oooo....oooo......",
        ".....oggggo..oggggo.....",
        "....ogwwwgoooogwwwgo....",
        "....ogwowggggggwowgo....",
        "...oggwwwggggggwwwggo...",
        "...oggggggggggggggggo...",
        "..oggggggggggggggggggo..",
        "..oggggggggggggggggggo..",
        ".oggggggggggggggggggggo.",
        ".oggggggggggggggggggggo.",
        ".ogggggggoooooogggggggo.",
        "oggggggggggggggggggggggo",
        "ognnnnnnnnnnnnnnnnnnnngo",
        "ognnnnnnnnnnnnnnnnnnnngo",
        "onnnnnnnnnnnnnnnnnnnnnno",
        ".onnnnnnnnnnnnnnnnnnnno.",
        "..onnnnnnnnnnnnnnnnnno..",
        "ooonnnnnnnnnnnnnnnnnnooo",
        "oggoonnnnnnnnnnnnnnooggo",
        "ogggoonnnnnnnnnnnnoogggo",
        "ooooo.oooooooooooo.ooooo",
        "........................",
    ];

    public static readonly string[] Snail =
    [
        "........................",
        ".........oooooo.........",
        ".......ookkkkkkoo.......",
        "......okkkeeeekkko......",
        ".....okkeeooooeekko.....",
        ".....okeeokkkkoeeko.....",
        "....okkeokkeekkoekko....",
        "....okeokkeooekkoeko....",
        "....okeokeokkoekoeko....",
        "....okeokeokkoekoeko....",
        "....okeokkeooekkoeko....",
        "....okkeokkeekkoekko....",
        ".....okeeokkkkoeeko.....",
        ".oo..okkeeooooeekko.....",
        "oiio..okkkeeeekkko......",
        "oiio...ookkkkkkoo.......",
        "oiioooooooooooooooo.....",
        "oiiiiiiiiiiiiiiiiiio....",
        "oiiiiiiiiiiiiiiiiiiio...",
        "oiiiiiiiiiiiiiiiiiiiio..",
        ".oiiiiiiiiiiiiiiiiiiio..",
        "..ooooooooooooooooooo...",
        "........................",
        "........................",
    ];

    public static readonly string[] Octopus =
    [
        "........................",
        "........................",
        "..........oooo..........",
        ".......ooovvvvooo.......",
        ".....oovvvvvvvvvvoo.....",
        "....ovvvvvvvvvvvvvvo....",
        "...ovvvvvvvvvvvvvvvjo...",
        "..ovvvvvvvvvvvvvvvjjjo..",
        "..ovvvvvvvvvvvvvvjjjjo..",
        ".ovvoovvvvvvvvvvjjoojjo.",
        ".ovvoovvvvvvvvvjjjoojjo.",
        ".ovvvvvvvvvvvvjjjjjjjjo.",
        ".ovvvvvvoovvvjoojjjjjjo.",
        "ovvvvvvvvvvvjjjjjjjjjjjo",
        "ovvvvvvvvvvjjjjjjjjjjjjo",
        "ojjjjjjjjjjjjjjjjjjjjjjo",
        "oojjoojjoojjjjoojjoojjoo",
        ".ojjo.ojjo.oo.ojjo.ojjo.",
        ".ojjo.ojjo.oo.ojjo.ojjo.",
        "ojjo..ojjo....ojjo..ojjo",
        "ojjo..ojjoooooojjo..ojjo",
        "ooo....ojjjjjjjjo....ooo",
        "........oooooooo........",
        "........................",
    ];

    public static readonly string[] Turtle =
    [
        "........................",
        "........................",
        "........................",
        "........oooooooo........",
        "......oonnnnnnnnoo......",
        ".....onnnnnnnnnnnno.....",
        "....onnggnnnnnnggnno....",
        "...onnggggnnnnggggnno...",
        "..onnggggggggggggggnno..",
        "..onggggnnggggnnggggno..",
        ".onggnnggggggggggnnggno.",
        ".ongggggggnnnngggggggno.",
        ".onggggnnggggggnnggggno.",
        "oonnggggggggggggggggnnoo",
        "ohhonnggggnnnnggggnnohho",
        "ohhhonnggggggggggnnohhho",
        "ohwhhonnnnnnnnnnnnohhwho",
        "ohhhhhoooooooooooohhhhho",
        ".ohhhho..........ohhhho.",
        "..ohhho.oooooooo.ohhho..",
        "...ooooohhhhhhhhooooo...",
        ".......ohhhhhhhho.......",
        ".......oooooooooo.......",
        "........................",
    ];

    public static readonly string[] Bat =
    [
        "........................",
        "..oo................oo..",
        ".ojjo...oooooooo...ojvo.",
        ".ojjjoojjjjjjjjjjoojvvo.",
        ".ojjjjjjjjjjjjjjjjjvvvo.",
        "..ojjjjjjjjjjjjjjjvvvo..",
        "..ojjjjjjjjjjjjjjvvvvo..",
        ".ojjoojjjjjjjjjjvvoovvo.",
        ".ojjoojjjjjjjjjvvvoovvo.",
        ".ojjjjjjjjjjjjvvvvvvvvo.",
        ".ojjjwwjjjjjjvvvvwwvvvo.",
        "ojjjjwwjjjjjvvvvvwwvvvvo",
        "ovvjjjjjjjjvvvvvvvvvvvvo",
        "ovvvjjjjjjvvvvvvvvvvvvvo",
        "ovvvvojjjvvvvvvvvvovvvvo",
        "ovvvvvojvvvvvvvvvovvvvvo",
        "ovvvvvvovvvvvvvvovvvvvvo",
        ".ovvvvvovvvvvvvvovvvvvo.",
        "..ovvvvovvvvvvvvovvvvo..",
        "...ovvvovvvvvvvvovvvo...",
        "....ovvoovvvvvvoovvo....",
        ".....ooo.ovvvvo.ooo.....",
        "..........oooo..........",
        "........................",
    ];

    /// <summary>Every level the menu ships, with the shuffle seed its .tres resource carries.</summary>
    public static IEnumerable<object[]> Shipped()
    {
        yield return ["toadstool", Toadstool, 20260809];
        yield return ["cherries", Cherries, 20260810];
        yield return ["balloon", Balloon, 20260811];
        yield return ["sailboat", Sailboat, 20260812];
        yield return ["cactus", Cactus, 20260813];
        yield return ["rocket", Rocket, 20260814];
        yield return ["lion", Lion, 20260815];
        yield return ["tiger", Tiger, 20260816];
        yield return ["elephant", Elephant, 20260817];
        yield return ["giraffe", Giraffe, 20260818];
        yield return ["zebra", Zebra, 20260819];
        yield return ["rhino", Rhino, 20260820];
        yield return ["hippo", Hippo, 20260821];
        yield return ["gorilla", Gorilla, 20260822];
        yield return ["monkey", Monkey, 20260823];
        yield return ["kangaroo", Kangaroo, 20260824];
        yield return ["koala", Koala, 20260825];
        yield return ["panda", Panda, 20260826];
        yield return ["bear", Bear, 20260827];
        yield return ["penguin", Penguin, 20260828];
        yield return ["walrus", Walrus, 20260829];
        yield return ["crocodile", Crocodile, 20260830];
        yield return ["snake", Snake, 20260831];
        yield return ["parrot", Parrot, 20260832];
        yield return ["flamingo", Flamingo, 20260833];
        yield return ["apple", Apple, 20260834];
        yield return ["pear", Pear, 20260835];
        yield return ["banana", Banana, 20260836];
        yield return ["orange", Orange, 20260837];
        yield return ["lemon", Lemon, 20260838];
        yield return ["strawberry", Strawberry, 20260839];
        yield return ["grapes", Grapes, 20260840];
        yield return ["watermelon", Watermelon, 20260841];
        yield return ["pineapple", Pineapple, 20260842];
        yield return ["peach", Peach, 20260843];
        yield return ["kiwi", Kiwi, 20260844];
        yield return ["avocado", Avocado, 20260845];
        yield return ["tomato", Tomato, 20260846];
        yield return ["carrot", Carrot, 20260847];
        yield return ["broccoli", Broccoli, 20260848];
        yield return ["corn", Corn, 20260849];
        yield return ["eggplant", Eggplant, 20260850];
        yield return ["pumpkin", Pumpkin, 20260851];
        yield return ["chilli", Chilli, 20260852];
        yield return ["onion", Onion, 20260853];
        yield return ["car", Car, 20260854];
        yield return ["taxi", Taxi, 20260855];
        yield return ["bus", Bus, 20260856];
        yield return ["truck", Truck, 20260857];
        yield return ["train", Train, 20260858];
        yield return ["tram", Tram, 20260859];
        yield return ["fire_engine", FireEngine, 20260860];
        yield return ["ambulance", Ambulance, 20260861];
        yield return ["police_car", PoliceCar, 20260862];
        yield return ["bicycle", Bicycle, 20260863];
        yield return ["motorbike", Motorbike, 20260864];
        yield return ["traffic_light", TrafficLight, 20260865];
        yield return ["no_entry", NoEntry, 20260866];
        yield return ["cone", Cone, 20260867];
        yield return ["street_lamp", StreetLamp, 20260868];
        yield return ["hydrant", Hydrant, 20260869];
        yield return ["digger", Digger, 20260870];
        yield return ["crane", Crane, 20260871];
        yield return ["skyscraper", Skyscraper, 20260872];
        yield return ["fuel_pump", FuelPump, 20260873];
        yield return ["slime", Slime, 20260874];
        yield return ["chick", Chick, 20260875];
        yield return ["kitten", Kitten, 20260876];
        yield return ["bunny", Bunny, 20260877];
        yield return ["fox", Fox, 20260878];
        yield return ["dragon", Dragon, 20260879];
        yield return ["ghost", Ghost, 20260880];
        yield return ["star", Star, 20260881];
        yield return ["cloud", Cloud, 20260882];
        yield return ["axolotl", Axolotl, 20260883];
        yield return ["jellyfish", Jellyfish, 20260884];
        yield return ["owlet", Owlet, 20260885];
        yield return ["hedgehog", Hedgehog, 20260886];
        yield return ["unicorn", Unicorn, 20260887];
        yield return ["sheep", Sheep, 20260888];
        yield return ["frog", Frog, 20260889];
        yield return ["snail", Snail, 20260890];
        yield return ["octopus", Octopus, 20260891];
        yield return ["turtle", Turtle, 20260892];
        yield return ["bat", Bat, 20260893];
    }

    /// <summary>
    /// Numbers the colours the way <c>LevelLoader</c> does, in the order they are first met,
    /// reading left to right and top to bottom, so a seeded scramble here matches the game's.
    /// </summary>
    public static LevelGrid Grid(string[] rows)
    {
        int width = rows[0].Length;
        var targets = new List<int>(width * rows.Length);
        var indices = new Dictionary<char, int>();

        foreach (string row in rows)
        {
            foreach (char symbol in row)
            {
                if (symbol == Boards.Hole)
                {
                    targets.Add(LevelGrid.Empty);
                    continue;
                }

                if (!indices.TryGetValue(symbol, out int index))
                {
                    index = indices.Count;
                    indices[symbol] = index;
                }

                targets.Add(index);
            }
        }

        return new LevelGrid(width, rows.Length, targets);
    }
}
