"""The hand-authored level pictures, one character per cell.

A sprite is a square block of characters. A '.' is a hole (the game draws nothing there) and every
other character is a key into PALETTE, which becomes one sphere colour. scripts/make_level_sprites.py
renders these to PNGs; scripts/import_level.py is what decides whether a rendered one is a level.

New art is 24x24. The first six pictures are still 16x16 and are due a redraw; nothing in the game
cares (src/BoardView.cs fits whatever grid the PNG describes), so the two sizes coexist until then.

Three rules bound what can be drawn here, all of them enforced downstream:

  * more than 24 filled cells, so the picture outlasts a tray
  * two to eight colours
  * no colour on more than half the filled cells, or the scramble cannot avoid leaving some cell
    already sitting on its target

The last one is the one that bites. A big single-colour body wants an outline, shading, or a
second material to split it, and `make_level_sprites.py` prints the share of every sprite it draws.
"""

PALETTE = {
    "O": (0x2B, 0x22, 0x33),  # outline
    "R": (0xE0, 0x45, 0x5A),  # red
    "D": (0xA8, 0x2F, 0x48),  # deep red
    "W": (0xF7, 0xF2, 0xE8),  # white
    "S": (0xEF, 0xD9, 0xA8),  # straw
    "T": (0xC9, 0xA8, 0x78),  # straw shadow
    "G": (0x63, 0xC1, 0x67),  # green
    "N": (0x3A, 0x8A, 0x50),  # deep green
    "B": (0x3F, 0x7E, 0xD8),  # blue
    "C": (0x7E, 0xD0, 0xF0),  # pale blue
    "Y": (0xF2, 0xC9, 0x4C),  # yellow
    "A": (0xF0, 0x8A, 0x3C),  # orange
    "K": (0xA9, 0x71, 0x3F),  # wood
    "E": (0x7A, 0x4E, 0x2A),  # wood shadow
    "P": (0xF0, 0x8F, 0xB8),  # blossom
    "L": (0xD5, 0xD8, 0xE0),  # steel
    "M": (0x8A, 0x92, 0xA6),  # slate
    "U": (0x2A, 0x4E, 0x96),  # deep blue
    "V": (0x8A, 0x5A, 0xC8),  # violet
    "H": (0xF6, 0xC7, 0xA0),  # sand
    "J": (0x5F, 0x3E, 0x8F),  # deep violet
    "X": (0x3E, 0x42, 0x52),  # asphalt
    "I": (0x6E, 0xD7, 0xC0),  # mint
}

# --------------------------------------------------------------------------- the first six

TOADSTOOL = [
    "................",
    ".....OOOOOO.....",
    "...OORRRRRROO...",
    "..ORWWRRRRWWRO..",
    ".ORRWWRRRRWWRRO.",
    ".ORRRRRRRRRRDDO.",
    "OORRRRWWWWRRDDDO",
    "ORRWRRWWWWRRWDDO",
    "ORRWRRRWWRRRWDDO",
    "OOOOOOOOOOOOOOOO",
    "...OSSSSSSSSO...",
    "...OSOOSSOOSO...",
    "...OSOOSSOOSO...",
    "...OSSSSSSTTO...",
    "...OSSSSSTTTO...",
    "....OOOOOOOO....",
]

CHERRIES = [
    "................",
    "..........GG....",
    ".........GGGN...",
    "........GGNN....",
    ".......GGG......",
    ".......G.G......",
    "......G...G.....",
    ".....G.....G....",
    "....G.......G...",
    "...G........G...",
    "..OOO......OOO..",
    ".ORRRO....ORRRO.",
    "ORWRRDO..ORWRRDO",
    "ORRRRDO..ORRRRDO",
    ".ORRDO....ORRDO.",
    "..OOO......OOO..",
]

BALLOON = [
    "................",
    "......OOOO......",
    "....OYBBBBYO....",
    "...OYYBBBBYYO...",
    "..ORYYBBBBYYRO..",
    ".ORRYYBBBBYYRRO.",
    ".ORRYYBBBBYYRRO.",
    "..ORYYBBBBYYRO..",
    "...OYYBBBBYYO...",
    "....OYBBBBYO....",
    ".....OOOOOO.....",
    "......E..E......",
    ".....OKKKKO.....",
    ".....OKKEEO.....",
    ".....OOOOOO.....",
    "................",
]

SAILBOAT = [
    "................",
    "........K.......",
    ".......WK.......",
    "......WWKR......",
    ".....WWWKRR.....",
    "....WWWWKRRR....",
    "...WWWWWKRRRR...",
    "..WWWWWWKRRRR...",
    ".WWWWWWWKRRRRR..",
    ".WWWWWWWKRRRRR..",
    "..OOOOOOOOOOOO..",
    "..OKKKKKKKKKKO..",
    "...OKKKKKKKKO...",
    "....OOOOOOOO....",
    "BCCBBBCCBBBCCBBB",
    "BBBBBBBBBBBBBBBB",
]

CACTUS = [
    ".......PP.......",
    "......GPPN......",
    "......GGNN......",
    "......GGNN......",
    "..PPN.GGNN......",
    "..GGN.GGNN.PPN..",
    "..GGN.GGNN.GGN..",
    "..GGN.GGNN.GGN..",
    "..GGGGGGNN.GGN..",
    "......GGGGGGNN..",
    "......GGNN......",
    "......GGNN......",
    "...KKKKKKKKKE...",
    "....KKKKKKKE....",
    "....KKKKKKEE....",
    ".....EEEEEE.....",
]

ROCKET = [
    ".......OO.......",
    "......ORRO......",
    "......ORRO......",
    ".....ORRRRO.....",
    ".....OLLLLO.....",
    ".....OLCCLO.....",
    ".....OLCCLO.....",
    ".....OLLLLO.....",
    "...OROLLLLORO...",
    "..ORROLLLLORRO..",
    ".ORRROLLLLORRRO.",
    ".OOOOOLLLLOOOOO.",
    ".....OOOOOO.....",
    "......YYYY......",
    "......YAAY......",
    ".......AA.......",
]

ORIGINALS = {
    "toadstool": TOADSTOOL,
    "cherries": CHERRIES,
    "balloon": BALLOON,
    "sailboat": SAILBOAT,
    "cactus": CACTUS,
    "rocket": ROCKET,
}

# --------------------------------------------------------------------------- the zoo

LION = [
    "........................",
    "...OO.OOOOOOOOOOOO.OO...",
    "..OAAOOAAAAAAAAAAOOAAO..",
    "..OAAAAAAAAAAAAAAAAAAO..",
    "..OAAAAAAAAAAAAAAAAAAO..",
    "..OAAAOOOOOOOOOOOOAAAO..",
    ".OAAAOSSSSSSSSSSSSOAAAO.",
    ".OAAAOSSSSSSSSSSSSOAAAO.",
    ".OAAOSSWWSSSSSSWWSSOAAO.",
    ".OAAOSSWOSSSSSSOWSSOAAO.",
    ".OAAOSSSSSSSSSSSSSSOAAO.",
    ".OAAOSSSSOOOOOOSSSSOAAO.",
    ".OAAAOSSSSOTTOSSSSOAAAO.",
    "..OAAAOSSTTTTTTSSOAAAO..",
    "..OAAAAOSSSSSSSSOAAAAO..",
    "...OAAAAAAAAAAAAAAAAO...",
    "....OOAAAAAAAAAAAAOO....",
    "......OOAAAAAAAAOO......",
    ".......OSSSSSSSSO.......",
    "......OSSSSSSSSSSO......",
    "......OSSSSSSSSSSO......",
    ".......OSSSSSSSSO.......",
    "........OOOOOOOO........",
    "........................",
]

TIGER = [
    "........................",
    "........................",
    "....OOOO........OOOO....",
    "...OAAAAO......OAAAAO...",
    "...OAOOAOOOOOOOOAOOAO...",
    "...OAAAOAAAAAAAAOAAAO...",
    "....OOOAAOAAAAOAAOOO....",
    "...OOAAAAAAAAAAAAAAOO...",
    "..OAAOAAAOAAAAOAAAOAAO..",
    "..OAAAWWOAAAAAAOWWAAAO..",
    "..OAAAWOOAAAAAAOOWAAAO..",
    "..OAAOAAASSSSSSAAAOAAO..",
    "..OAAOAASSSOOSSSAAOAAO..",
    "...OAAASSSSOOSSSSAAAO...",
    "...OAAOASSWWWWSSAOAAO...",
    "....OAAASSSSSSSSAAAO....",
    ".....OOAAOAAAAOAAOO.....",
    "......OSSSSSSSSSSO......",
    ".....OASSSSSSSSSSAO.....",
    ".....OAAOSSSSSSOAAO.....",
    ".....OAAASSSSSSAAAO.....",
    "......OAAOAAAAOAAO......",
    ".......OOOOOOOOOO.......",
    "........................",
]

ELEPHANT = [
    "........................",
    "........................",
    "..OOOOOO........OOOOOO..",
    ".OLLLLLLOOOOOOOOLLLLLLO.",
    ".OLLLLLLOMMMMMMOLLLLLLO.",
    ".OLLLLLLOMMMMMMOLLLLLLO.",
    ".OLLLLLLMMMMMMMMLLLLLLO.",
    ".OLLLLLLMWWMMWWMLLLLLLO.",
    ".OLLLLLLMWOMMOWMLLLLLLO.",
    ".OLLLLLLMMMMMMMMLLLLLLO.",
    ".OLLLLLLMMMMMMMMLLLLLLO.",
    ".OLLLLLLMMMMMMMMLLLLLLO.",
    ".OLLLLLLMMMMMMMMLLLLLLO.",
    "..OLLLLOMMMMMMMMOLLLLO..",
    "...OOOOOMMMMMMMMOOOOO...",
    "......WWOMMMMMMOWW......",
    "......WWOMMMMMMOWW......",
    ".......WOMMMMMMOW.......",
    "........OMMMMMMO........",
    "........OMMMMMMO........",
    ".........OMMMMO.........",
    ".........OMMMMO.........",
    "..........OOOO..........",
    "........................",
]

GIRAFFE = [
    "........................",
    "..............OO.OO.....",
    "..............OKOKO.....",
    ".............OOSSSOO....",
    ".............OSSSSSO....",
    ".............OSOSOSO....",
    ".............OSSSSSO....",
    ".............OOSSSOO....",
    "..............OSSKO.....",
    "..............OKSSO.....",
    "..............OSSSO.....",
    "..............OSKSO.....",
    "..............OSSSO.....",
    "......OOOOOOOOOSSKOO....",
    "......OSSKSSSSSSSSSO....",
    "......OSSSSSKKSSSSSO....",
    "......OSKSSSSSSSKSSO....",
    "......OSSSSKSSSSSSSO....",
    "......OSSKSSSSKSSSSO....",
    "......OOSSOOOOOOSSOO....",
    ".......OSSO....OSSO.....",
    ".......OSSO....OSSO.....",
    ".......OEEO....OEEO.....",
    ".......OOOO....OOOO.....",
]

ZEBRA = [
    "........................",
    ".......OO......OO.......",
    "......OMMO....OMMO......",
    "......OMMOOOOOOMMO......",
    ".....OOMMMOOOOMMMOO.....",
    "....OOWWWMMMMMMWWWOO....",
    "...OWWOWWOMMMMOWWOWWO...",
    "...OWWOWWWOMMOWWWOWWO...",
    "...OWOOWWWWWWWWWWOOWO...",
    "...OWWOWWWWWWWWWWOWWO...",
    "..OWWOOWWWWWWWWWWOOWWO..",
    "..OWWWOOWWWWWWWWOOWWWO..",
    "..OWWOOOOWWWWWWOOOOWWO..",
    "..OWWWOOWWWWWWWWOOWWWO..",
    "..OWWWWWWWWWWWWWWWWWWO..",
    "...OWWWWMMMMMMMMWWWWO...",
    "...OWWWMMMMMMMMMMWWWO...",
    "....OWMMMMMMMMMMMMWO....",
    "....OMMMOMMMMMMOMMMO....",
    ".....OMMMMMMMMMMMMO.....",
    "......OOMMMMMMMMOO......",
    ".......OOOOOOOOOO.......",
    "........................",
    "........................",
]

RHINO = [
    "........................",
    "...OOOO..........OOOO...",
    "..OLLLLO........OLLLLO..",
    "..OLLLLOOOOOOOOOOLLLLO..",
    "..OLLLLLLLLLLLLLLLLLLO..",
    "...OLLLLLLLLLLLLLLLLO...",
    "....OLLLLLLLLLLLLLLO....",
    "....OLLLLLLLLLLLLLLO....",
    "....OLWWLLLLLLLLWWLO....",
    "....OLWOLLLLLLLLOWLO....",
    "....OLLLLLLLLLLLLLLO....",
    ".....OLLLLLWWLLLLLO.....",
    ".....OLLLLOWWOLLLLO.....",
    ".....OLLLLOWWOLLLLO.....",
    "......OLLLOWWOLLLO......",
    "......OMMMMMMMMMMO......",
    "......OMMMMMMMMMMO......",
    "......OMMOMMMMOMMO......",
    "......OMMMMMMMMMMO......",
    ".......OMMMMMMMMO.......",
    ".......OOMMMMMMOO.......",
    "........OOOOOOOO........",
    "........................",
    "........................",
]

HIPPO = [
    "........................",
    "........................",
    "....OOO..........OOO....",
    "...OVVVO........OVVVO...",
    "...OVPVOOOOOOOOOOVPVO...",
    "...OVVVOVVVVVVVVOVVVO...",
    "....OOOVVVVVVVVVVOOO....",
    "...OOVVVVVVVVVVVVVVOO...",
    "..OVVVWWOVVVVVVOWWVVVO..",
    "..OVVVWOOVVVVVVOOWVVVO..",
    "..OVVVVVVVVVVVVVVVVVVO..",
    "..OVVVVPPPPPPPPPPVVVVO..",
    "..OVVVPPPPPPPPPPPPVVVO..",
    "..OVVVPPOPPPPPPOPPVVVO..",
    "..OVVVPPOPPPPPPOPPVVVO..",
    "...OVVPPPPPPPPPPPPVVO...",
    "....OVPPPPPPPPPPPPVO....",
    "....OVVPPPPPPPPPPVVO....",
    ".....OVVVVVVVVVVVVO.....",
    "......OVVVVVVVVVVO......",
    "......OVVOOOOOOVVO......",
    "......OVVO....OVVO......",
    "......OOOO....OOOO......",
    "........................",
]

GORILLA = [
    "........................",
    "........................",
    ".....OOOOOOOOOOOOOO.....",
    "....OEEEEEEEEEEEEEEO....",
    "...OEEEEEEEEEEEEEEEEO...",
    "..OOEEOOOOOOOOOOOOEEOO..",
    ".OEEOEMMMMMMMMMMMMEOEEO.",
    ".OEEOEMOOMMMMMMOOMEOEEO.",
    ".OEEOEMWWMMMMMMWWMEOEEO.",
    ".OEEOEMWOMMMMMMOWMEOEEO.",
    "..OOEEMMMMMMMMMMMMEEOO..",
    "...OEEMMMOOMMOOMMMEEO...",
    "...OEEEMMMMMMMMMMEEEO...",
    "....OEEOOOMMMMOOOEEO....",
    "....OEEEEEEEEEEEEEEO....",
    "...OEEEEEEEEEEEEEEEEO...",
    "..OEEELLLLLLLLLLLLEEEO..",
    ".OEEEELLLLLLLLLLLLEEEEO.",
    ".OEEEEEEEEEEEEEEEEEEEEO.",
    "OEEEOEEEEEEEEEEEEEEOEEEO",
    "OEEEOEEEEEEEEEEEEEEOEEEO",
    ".OEEOEEEEEEEEEEEEEEOEEO.",
    "..OOEEEEEEEEEEEEEEEEOO..",
    "....OOOOOOOOOOOOOOOO....",
]

MONKEY = [
    "........................",
    "..OOOO..........OOOO....",
    ".OKKKKO........OKKKKO...",
    ".OKHHKO.OOOOOO.OKHHKO...",
    ".OKHHKOOKKKKKKOOKHHKO...",
    ".OKKKKOKKKKKKKKOKKKKO...",
    "..OOOOOKKKKKKKKOOOOO....",
    "......OKKWWKKWWKKO......",
    "......OKKWOKKOWKKO......",
    "......OKKHHHHHHKKO......",
    "......OKHHHOOHHHKO......",
    ".......OHHHHHHHHO.......",
    "........OOOOOOOO........",
    "......OOOKKKKKKOOO......",
    ".....OKKKKKKKKKKKKO.....",
    "....OKKKOHHHHHHOKKKO....",
    "....OKKOHHHHHHHHOKKO....",
    "....OKKOHHHHHHHHOKKO....",
    "....OKKKOHHHHHHOKKKO....",
    ".....OKKKKKKKKKKKKO.....",
    "......OOKKKKKKKKOO......",
    "........OKKOOKKO........",
    "........OOO..OOO........",
    "........................",
]

KANGAROO = [
    "........................",
    ".....OO.OO..............",
    "....OHOOHO..............",
    "....OHOOHO..............",
    "....OKKKKO..............",
    "...OKKKKKKO.............",
    "...OKWOKKKO.............",
    "..OKKKKKKKO.............",
    "..OOKKKKKKO.............",
    "....OKKKKO..............",
    "....OKKKKOO.............",
    "...OKHHHKKKO............",
    "..OKHHHHHKKKO...........",
    "..OKHHHHHHKKKO..........",
    "..OKHHHHHHHKKKO.........",
    "..OKHHHHHHHKKKKO........",
    "..OKKHHHHHHKKKKKO.......",
    "..OKKKHHHHKKKKKKKO......",
    "..OKKKKKKKKKKKKKKKO.....",
    "..OKKKKOOOOKKKKEEEEO....",
    "..OKKKO...OKKKOEEEEEO...",
    "..OKKKO...OKKKO.OOEEEO..",
    ".OKKKKO...OKKKO...OOOOO.",
    ".OOOOOO...OOOOO.........",
]

KOALA = [
    "..OOOO............OOOO..",
    ".OLLLLO..........OLLLLO.",
    "OLWWWWLO........OLWWWWLO",
    "OLWWWWLLOOOOOOOOLLWWWWLO",
    "OLWWWWLLLLLLLLLLLLWWWWLO",
    ".OLLLLLLLLLLLLLLLLLLLLO.",
    "..OOLLLLLLLLLLLLLLLLOO..",
    "....OLLLLLLLLLLLLLLO....",
    "....OLWOLLLLLLLLOWLO....",
    "....OLLLLLLLLLLLLLLO....",
    "....OLLLLOOOOOOLLLLO....",
    ".....OLLOOOOOOOOLLO.....",
    ".....OLLOOOOOOOOLLO.....",
    "......OLLOOOOOOLLO......",
    "......OLLLLLLLLLLO......",
    ".....OLLLLLLLLLLLLO.....",
    "....OLLLMMMMMMMMLLLO....",
    "...OLLLMMMMMMMMMMLLLO...",
    "...OLLMMMMMMMMMMMMLLO...",
    "...OLLMMMMMMMMMMMMLLO...",
    "...OLLLMMMMMMMMMMLLLO...",
    "....OLLLMMMMMMMMLLLO....",
    ".....OOOOOOOOOOOOOO.....",
    "........................",
]

PANDA = [
    "........................",
    "....OOO..........OOO....",
    "...OMMMO........OMMMO...",
    "...OMMMO........OMMMO...",
    "....OOOOOOOOOOOOOOOO....",
    "...OOWWWWWWWWWWWWWWOO...",
    "..OOWWWWWWWWWWWWWWWWOO..",
    "..OWWOOOWWWWWWWWOOOWWO..",
    "..OWOOOOOWWWWWWOOOOOWO..",
    "..OWOOWOOWWWWWWOOWOOWO..",
    "..OWOOOOOWWWWWWOOOOOWO..",
    "..OWWOOOWWWOOWWWOOOWWO..",
    "..OWWWWWWWOOOOWWWWWWWO..",
    "...OWWWWWWWOOWWWWWWWO...",
    "....OOWWWWWWWWWWWWOO....",
    "......OOOOOOOOOOOO......",
    "....OOOMWWWWWWWWMOOO....",
    "...OOMMMWWWWWWWWMMMOO...",
    "...OOMMMWWWWWWWWMMMOO...",
    "...OOMMMWWWWWWWWMMMOO...",
    "....OOOMWWWWWWWWMOOO....",
    "...OOOOOOWWWWWWOOOOOO...",
    "...OOOOOOOOOOOOOOOOOO...",
    "........................",
]

BEAR = [
    "........................",
    "...OOOO..........OOOO...",
    "..OKKKKO........OKKKKO..",
    "..OKEEKO........OKEEKO..",
    "..OKKKKOOOOOOOOOOKKKKO..",
    "...OKKKKKKKKKKKKKKKKO...",
    "..OKKKKKKKKKKKKKKKKKKO..",
    ".OKKKKKKKKKKKKKKKKKKKKO.",
    ".OKKWWKKKKKKKKKKKKWWKKO.",
    ".OKKWOKKKKKKKKKKKKOWKKO.",
    ".OKKKKKKKKKKKKKKKKKKKKO.",
    ".OKKKKHHHHHHHHHHHHKKKKO.",
    ".OKKKHHHHHHHHHHHHHHKKKO.",
    "..OKKHHHOOOOOOOOHHHKKO..",
    "..OKKHHHHHHHHHHHHHHKKO..",
    "...OKKHHHHHHHHHHHHKKO...",
    "....OKKKKKKKKKKKKKKO....",
    ".....OOKHHHHHHHHKOO.....",
    "...OOKKHHHHHHHHHHKKOO...",
    "..OKKKHHHHHHHHHHHHKKKO..",
    "..OKKHHHHHHHHHHHHHHKKO..",
    "..OKKHHHHHHHHHHHHHHKKO..",
    "...OKKHHHHHHHHHHHHKKO...",
    "....OOOOOOOOOOOOOOOO....",
]

PENGUIN = [
    "........................",
    ".........OOOOOO.........",
    ".......OOUUUUUUOO.......",
    "......OUUUUUUUUUUO......",
    "......OUUUUUUUUUUO......",
    "......OUUWWOOWWUUO......",
    "......OUUWWOOWWUUO......",
    "......OUUWWYYWWUUO......",
    ".....OUUUWWYYWWUUUO.....",
    "....OUUUUWWWWWWUUUUO....",
    "...OUUUUWWWWWWWWUUUUO...",
    "..OUUUUWWWWWWWWWWUUUUO..",
    "..OUUUWWWWWWWWWWWWUUUO..",
    "..OUUUWWWWWWWWWWWWUUUO..",
    "..OUUUWWWWWWWWWWWWUUUO..",
    "..OUUUWWWWWWWWWWWWUUUO..",
    "..OUUUWWWWWWWWWWWWUUUO..",
    "..OUUUUWWWWWWWWWWUUUUO..",
    "...OUUUUWWWWWWWWUUUUO...",
    "....OUUUUWWWWWWUUUUO....",
    ".....OOUUUUUUUUUUOO.....",
    "......OYYYOOOOYYYO......",
    ".......OOOO..OOOO.......",
    "........................",
]

WALRUS = [
    "........................",
    "........................",
    "....OOOOOOOOOOOOOOOO....",
    "..OOEEEEEEEEEEEEEEEEOO..",
    ".OEEEEEEEEEEEEEEEEEEEEO.",
    ".OEEEEEEEEEEEEEEEEEEEEO.",
    ".OEEWWEEEEEEEEEEEEWWEEO.",
    ".OEEWOEEEEEEEEEEEEOWEEO.",
    ".OEEEEEEEEEEEEEEEEEEEEO.",
    ".OEEEEKKKKKKKKKKKKEEEEO.",
    "..OEEKKKKKKKKKKKKKKEEO..",
    "..OEKKKKKKKKKKKKKKKKEO..",
    "..OEKKKKKOOOOOOKKKKKEO..",
    "..OEKKKKKKKKKKKKKKKKEO..",
    "..OEKKWKKKKKKKKKKWKKEO..",
    "..OEKKWKKKKKKKKKKWKKEO..",
    "...OKWWKKKKKKKKKKWWKO...",
    "...OKWKKKKKKKKKKKKWKO...",
    "...OEEEEEEEEEEEEEEEEO...",
    "..OEEEEEEEEEEEEEEEEEEO..",
    "..OEEEEEEEEEEEEEEEEEEO..",
    "...OEEEEEEEEEEEEEEEEO...",
    "....OOOOOOOOOOOOOOOO....",
    "........................",
]

CROCODILE = [
    "........................",
    "........................",
    "........................",
    "........................",
    "..OOOOOOOOO.............",
    ".ONNNNNNNNNOO...........",
    ".OGYGGGGGGGGGOOOO.......",
    ".OWOWOWOWOWGGGNNNNOO....",
    ".OGGGGGGGGGGGNNGGNNNGOO.",
    "..OOOOOOOOOGGGGGGNNNNNGO",
    "..........OGGNNGGGGGGNGO",
    "..........OGGGGGGGGNNGGO",
    "..........OONNGGGGGGGGGO",
    "...........OGGGGGGGGGOO.",
    "...........OGOOGGGOGO...",
    "..........OGGO.OGGOGGO..",
    "..........ONNO.ONNONNO..",
    "..........OOOO.OOO.OOO..",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
]

SNAKE = [
    "........................",
    "..OOOO..................",
    ".OGGGGO.................",
    ".OGWOGOOOOOOOOOOO.......",
    ".OGGGGGGGGGGGGGGGGO.....",
    ".OORRGNNNNNNNNNNNGGO....",
    "...OOGGGGGGGGGGGGGGO....",
    "....OGYYYYYYYYYYYGGO....",
    "...OGGYYYYYYYYYYYYGO....",
    "...OGGNNNNNNNNNNNGGO....",
    "...OGGGGGGGGGGGGGGO.....",
    "..OGGGGGGGGGGGGGOO......",
    "..OGGNNNNNNNNNGGO.......",
    "..OGYYYYYYYYYYYGO.......",
    "..OGYYYYYYYYYYYGGO......",
    "..OGGNNNNNNNNNNGGO......",
    "..OGGGGGGGGGGGGGGO......",
    "...OGGGGGGGGGGGGGO......",
    "...OGGNNNNNNNNNGGO......",
    "....OGYYYYYYYYYGO.......",
    "....OGGYYYYYYYGGO.......",
    ".....OGGGGGGGGGO........",
    "......OOOOOOOOO.........",
    "........................",
]

PARROT = [
    "........................",
    "........................",
    ".......OOOOOO...........",
    "......ORRRRRRO..........",
    ".....ORRRRRRRRO.........",
    "....ORWORRRRRRO.........",
    "...OYYORRRRRRRRO........",
    "...OYYYORRRRRRRO........",
    "....OYORRRRRRRRO........",
    ".....ORRRRRRRRRO........",
    ".....ORRRRBBBBOO........",
    ".....ORRRBBBBBBO........",
    ".....ORRRBBBBBBBO.......",
    ".....ORRRBBBBBBBBO......",
    "......ORRBBBBBBBBO......",
    "......ORRRBBBBBBBO......",
    "......ORRRRBBBBBBO......",
    ".......ORRRRBBBBBO......",
    ".......ORRRRRBBBBO......",
    "........OYYORRRRO.......",
    "........OYYYOOOOO.......",
    ".........OYO............",
    ".........OOO............",
    "........................",
]

FLAMINGO = [
    "........................",
    ".........OOOOO..........",
    "........OPPPPPO.........",
    ".......OPPWOPPPO........",
    "......OODPPPPPPO........",
    ".....ODDOOPPPPO.........",
    ".....OOO..OPPO..........",
    "..........OPPO..........",
    "..........OPPO..........",
    ".........OPPO...........",
    ".........OPPO...........",
    "........OPPO............",
    "......OOOPPOOO..........",
    ".....OPPPPPPPPOO........",
    "....OPPPPPPPPPPPO.......",
    "...OPDDDDDDPPPPPPO......",
    "...OPDDDDDDDDPPPPPO.....",
    "...OPDDDDDDDDPPPPPO.....",
    "....OPDDDDDDPPPPPO......",
    ".....OODDDDPPPPOO.......",
    ".......OOPPPPOO.........",
    ".........OPPO...........",
    ".........OPPO...........",
    ".........OOOO...........",
]

ZOO = {
    "lion": LION,
    "tiger": TIGER,
    "elephant": ELEPHANT,
    "giraffe": GIRAFFE,
    "zebra": ZEBRA,
    "rhino": RHINO,
    "hippo": HIPPO,
    "gorilla": GORILLA,
    "monkey": MONKEY,
    "kangaroo": KANGAROO,
    "koala": KOALA,
    "panda": PANDA,
    "bear": BEAR,
    "penguin": PENGUIN,
    "walrus": WALRUS,
    "crocodile": CROCODILE,
    "snake": SNAKE,
    "parrot": PARROT,
    "flamingo": FLAMINGO,
}

# --------------------------------------------------------------------------- fruit and veg

APPLE = [
    "........................",
    "..........OOOO..........",
    ".......OOOKKKKOOO.......",
    "......ONNNOKKONNNO......",
    "......ONNOKKKKONNO......",
    ".....OORRRRRRRRRROO.....",
    "...OORRRRRRRRRRRRRROO...",
    "..ORRRRRRRRRRRRRRRRDDO..",
    ".ORRRRRRRRRRRRRRRRDDDDO.",
    ".ORRWWRRRRRRRRRRRDWWDDO.",
    ".ORRWWRRRRRRRRRRDDWWDDO.",
    "ORRRRRRRRRRRRRRDDDDDDDDO",
    "ORRRRRRRRRRRRRDDDDDDDDDO",
    "ORRRRRRRRRRRRDDDDDDDDDDO",
    "ORRRRRRRRRRRDDDDDDDDDDDO",
    "ORRRRRRRRRRDDDDDDDDDDDDO",
    ".ORRRRRRRRDDDDDDDDDDDDO.",
    ".ORRRRRRRDDDDDDDDDDDDDO.",
    "..ORRRRRDDDDDDDDDDDDDO..",
    "...OORRDDDDDDDDDDDDOO...",
    ".....OOODDDDDDDDOOO.....",
    ".......OOOOOOOOOO.......",
    "........................",
    "........................",
]

PEAR = [
    "........................",
    "..........OOOO..........",
    ".......OOOKKKKOOO.......",
    "......ONNNOKKONNNO......",
    "......ONNOKKKKONNO......",
    "........OGGGGGGO........",
    ".......OGGGGGGGGO.......",
    "......OGGGGGGGGGGO......",
    ".....OGGGGGGGGGGGNO.....",
    ".....OGWGGGGGGGGWNO.....",
    "....OGGWGGGGGGGNWNNO....",
    "....OGGGGGGGGGNNNNNO....",
    "...OGGGGGGGGGNNNNNNNO...",
    "..OGGGGGGGGGNNNNNNNNNO..",
    "..OGGGGGGGGNNNNNNNNNNO..",
    ".OGGGGGGGGNNNNNNNNNNNNO.",
    ".OGGGGGGGNNNNNNNNNNNNNO.",
    ".OGGGGGGNNNNNNNNNNNNNNO.",
    "..OGGGGNNNNNNNNNNNNNNO..",
    "..OGGGNNNNNNNNNNNNNNNO..",
    "...OONNNNNNNNNNNNNNOO...",
    ".....OOOOOOOOOOOOOO.....",
    "........................",
    "........................",
]

BANANA = [
    "........................",
    "........................",
    ".........OOO............",
    "........OKKKO...........",
    ".......OYYYKO...........",
    "......OYYYYYO...........",
    ".....OYYSSYYO...........",
    ".....OYSSYYYO...........",
    "....OYSSSYYYO...........",
    "....OYSSSYYYYO..........",
    "....OYSSSSYYYYO.........",
    "....OYSSSSYYYYYO........",
    "....OYSSSSSYYYYYO.......",
    ".....OYSSSSSYYYYYO......",
    ".....OYYSSSSSYYYYYO.....",
    "......OYYSSSSSYYYYYO....",
    ".......OYYSSSSYYYYYYO...",
    "........OYYSSSSYYYYYO...",
    ".........OYYYSSSSYYYO...",
    "..........OOYYYSSSYYO...",
    "............OOYYYYYOO...",
    "..............OOOOO.....",
    "........................",
    "........................",
]

ORANGE = [
    "........................",
    "........................",
    "..........OOOO..........",
    ".......OOONNNNOOO.......",
    "......ONNNONNONNNO......",
    ".....OOAAAAAAAAAAOO.....",
    "....OAAAAAAAAAAAAAAO....",
    "...OAAAAAAAAAAAAAAAKO...",
    "..OAAAAAAAAAAAAAAAKKKO..",
    "..OAAWAAAAAAAAAAAKWKKO..",
    ".OAAWAAAAAAAAAAAKKKWKKO.",
    ".OAAAAAAAAAAAAAKKKKKKKO.",
    ".OAAAAAAAAAAAAKKKKKKKKO.",
    ".OAAAAAAAAAAAKKKKKKKKKO.",
    ".OAAAAAAAAAAKKKKKKKKKKO.",
    ".OAAAAAAAAAKKKKKKKKKKKO.",
    "..OAAAAAAAKKKKKKKKKKKO..",
    "..OAAAAAAKKKKKKKKKKKKO..",
    "...OAAAAKKKKKKKKKKKKO...",
    "....OAAKKKKKKKKKKKKO....",
    ".....OOKKKKKKKKKKOO.....",
    ".......OOOOOOOOOO.......",
    "........................",
    "........................",
]

LEMON = [
    "........................",
    "........................",
    "..........OOOO..........",
    "..........OGGO..........",
    ".........OYYYYO.........",
    "......OOOYYYYYYOOO......",
    ".....OYYYYYYYYYYYYO.....",
    "...OOYYYYYYYYYYYYYYOO...",
    "..OYYYYYYYYYYYYYYYSSSO..",
    ".OYYWYYYYYYYYYYYYSSWSSO.",
    ".OYYWYYYYYYYYYYYSSSWSSO.",
    "OYYYYYYYYYYYYYYSSSSSSSSO",
    "OYYYYYYYYYYYYYSSSSSSSSSO",
    "OYYYYYYYYYYYYSSSSSSSSSSO",
    "OYYYYYYYYYYYSSSSSSSSSSSO",
    ".OYYYYYYYYYSSSSSSSSSSSO.",
    ".OYYYYYYYYSSSSSSSSSSSSO.",
    "..OYYYYYYSSSSSSSSSSSSO..",
    "...OYYYYSSSSSSSSSSSSO...",
    "....OOYSSSSSSSSSSSOO....",
    "......OOSSSSSSSSOO......",
    ".......OOOOOOOOOO.......",
    "........................",
    "........................",
]

STRAWBERRY = [
    "........................",
    "........................",
    "..........OOOO..........",
    ".......OOONNNNOOO.......",
    "......ONNNNNNNNNNO......",
    ".....ONNNNNNNNNNNNO.....",
    "....OONNNNNNNNNNNNOO....",
    "...ORRRNNRRRRRRNNRRRO...",
    "..ORRRRRRRRRRRRRRRRRRO..",
    ".ORWRRRWRRRRRRRRWRRRWRO.",
    ".ORRRRRRRRRWWRRRRRRRRRO.",
    "ORWRRRWRRRRRRRRRRWRRRWRO",
    "ORRRRRRRRRWRRWRRRRRRRRRO",
    "ORWRDDDWDDDDDDDDWDDDRWRO",
    ".ODDDDDDDWDDDDWDDDDDDDO.",
    ".ODWDDDWDDDDDDDDWDDDWDO.",
    "..ODDDDDDDWDDWDDDDDDDO..",
    "..ODWDDDWDDDDDDWDDDWDO..",
    "...ODDDDDDDDDDDDDDDDO...",
    "....ODDDWDDDDDDWDDDO....",
    ".....OODDDDDDDDDDOO.....",
    ".......OOOOOOOOOO.......",
    "........................",
    "........................",
]

GRAPES = [
    "........................",
    "............OO..........",
    "...........OKKO.........",
    ".......OOOOOKKOOOOO.....",
    "......OVVVVOOOOVVVVO....",
    "......OVVVVO..OVVVVO....",
    "......OVVVVOOOOVVVVO....",
    "....OOVVVVOVVVVOVVVVOO..",
    "...OVVVVVOVVVVVVOVVVVVO.",
    "...OVVVVOVVVVVVVVOVVVVO.",
    "...OVVVVOVVVVVVVVOVVVVO.",
    "...OOOOOOVVVVVVVVOOOOOO.",
    "....OJJJOOOOOOOOOJJJO...",
    "...OJJJJOJJJJJJOJJJJJO..",
    "...OJJJJOJJJJJJOJJJJJO..",
    "...OOOOOOJJJJJJOOOOOO...",
    "....OJJJJOOOOOOJJJJO....",
    "....OJJJJJOOOJJJJJJO....",
    ".....OJJJJJJJJJJJJO.....",
    "......OJJJJJJJJJJO......",
    ".......OJJJJJJJJO.......",
    "........OOJJJJOO........",
    "..........OOOO..........",
    "........................",
]

WATERMELON = [
    "........................",
    "........................",
    "........................",
    ".....OOOOOOOOOOOOOO.....",
    "....ONNNNNNNNNNNNNNO....",
    "....OGGGGGGGGGGGGGGO....",
    "...OGGGGGGGGGGGGGGGGO...",
    "...OWWWWWWWWWWWWWWWWO...",
    "..OWWWWWWWWWWWWWWWWWWO..",
    "..ORRRRRRRRRRRRRRRRRRO..",
    "..ORRRORRRRRRRRORRRRRO..",
    "..ORRRRRRRORRRRRRRRRRO..",
    "...ODDDDDDDDDDDDDDDDO...",
    "...ODDDODDDDDODDDDDDO...",
    "....ODDDDDDDDDDDDDDO....",
    "....ODDDDDODDDDDODDO....",
    ".....ODDDDDDDDDDDDO.....",
    "......ODDDDODDDDDO......",
    ".......ODDDDDDDDO.......",
    "........ODDDDDDO........",
    ".........OODDOO.........",
    "...........OO...........",
    "........................",
    "........................",
]

PINEAPPLE = [
    "........................",
    "..........OOOO..........",
    ".........ONGGNO.........",
    "......OOOONGGNOOOO......",
    ".....ONNGONGGNOGNNO.....",
    "....ONNGOGGGGGGOGNNO....",
    "....ONGGOGGGGGGOGGNO....",
    ".....OOGGOGGGGOGGOO.....",
    "......OOOOYYYYOOOO......",
    ".....OOYYSYYYYSYYOO.....",
    "....OYYSYYSYYSYYSYYO....",
    "...OYSYYSYYSSYYSYYSYO...",
    "...OYYSYYSYYYYSYYSYYO...",
    "..OYSYYSYYSYYSYYSYYSYO..",
    "..OYYSYYSYYSSYYSYYSYYO..",
    "..OYSYYSYYSYYSYYSYYSYO..",
    "..OYYSYYSYYSSYYSYYSYYO..",
    "..OYSYYSYYSYYSYYSYYSYO..",
    "...OYYSYYSYYYYSYYSYYO...",
    "...OYSYYSYYSSYYSYYSYO...",
    "....OOYYSYYSSYYSYYOO....",
    "......OOOOOOOOOOOO......",
    "........................",
    "........................",
]

PEACH = [
    "........................",
    "........................",
    ".......OOOOOOOOOO.......",
    "......ONNNNOONNNNO......",
    "......ONNNOOOONNNO......",
    ".....OOPPPPPPPPPPOO.....",
    "....OPPPPPPPPPPPPPPO....",
    "...OPPPPPPPPPPPPPPPPO...",
    "..OPPPPPPPPPPPPPPPPDDO..",
    "..OPPWPPPPPPPPPPPPWDDO..",
    ".OPPWPPPPPPPPPPPPDDWDDO.",
    ".OPPPPPPPPPPPPPPDDDDDDO.",
    ".OPPPPPPPPPPPPPDDDDDDDO.",
    ".OPPPPPPPPPPPPDDDDDDDDO.",
    ".OPPPPPPPPPPPDDDDDDDDDO.",
    ".OPPPPPPPPPPDDDDDDDDDDO.",
    "..OPPPPPPPPDDDDDDDDDDO..",
    "..OPPPPPPPDDDDDDDDDDDO..",
    "...OPPPPPDDDDDDDDDDDO...",
    "....OPPPDDDDDDDDDDDO....",
    ".....OODDDDDDDDDDOO.....",
    ".......OOOOOOOOOO.......",
    "........................",
    "........................",
]

KIWI = [
    "........................",
    "........................",
    "......OOOOOOOOOOOO......",
    "....OOKKKKKKKKKKKKOO....",
    "...OKKKKKKKKKKKKKKKKO...",
    "..OKKGGGGGGGGGGGGGGKKO..",
    "..OKGGGGGGGGGGGGGGGGKO..",
    ".OKGGGGGGGGGGGGGGGGGGKO.",
    ".OKGGGGGWWWWWWWWGGGGGKO.",
    ".OKGGGGWWWWWWWWWWGGGGKO.",
    "OKGGGGWWWWWWWWWWWWGGGGKO",
    "OKGGGGWWWWWWWWWWWWGGGGKO",
    "OKGGGGWWWWWWWWWWWWGGGGKO",
    "OKGGGGWWWWWWWWWWWWGGGGKO",
    ".OKGGGGWWWWWWWWWWGGGGKO.",
    ".OKGGGGGWWWWWWWWGGGGGKO.",
    ".OKGGGGGGGGGGGGGGGGGGKO.",
    "..OKGGGGGGGGGGGGGGGGKO..",
    "..OKKGGGGGGGGGGGGGGKKO..",
    "...OKKKKKKKKKKKKKKKKO...",
    "....OOKKKKKKKKKKKKOO....",
    "......OOOOOOOOOOOO......",
    "........................",
    "........................",
]

AVOCADO = [
    "........................",
    "........................",
    "..........OOOO..........",
    "........OONNNNOO........",
    "......OONNNNNNNNOO......",
    ".....ONNGGGGGGGGNNO.....",
    "....ONGGGGGGGGGGGGNO....",
    "....ONGGGGGGGGGGGGNO....",
    "...ONGGGGGGGGGGGGGGNO...",
    "...ONGGGGGGGGGGGGGGNO...",
    "..ONGGGGGGGGGGGGGGGGNO..",
    "..ONGGGGGKKKKKKGGGGGNO..",
    ".ONGGGGGKKKKKKKKGGGGGNO.",
    ".ONGGGGKKKKKKKKKKGGGGNO.",
    ".ONGGGGKKKKKKKKKKGGGGNO.",
    ".ONGGGGKKKKKKKKKKGGGGNO.",
    ".ONGGGGGKKKKKKKKGGGGGNO.",
    "..ONGGGGGKKKKKKGGGGGNO..",
    "..ONGGGGGGGGGGGGGGGGNO..",
    "...ONNGGGGGGGGGGGGNNO...",
    "....OONNNNNNNNNNNNOO....",
    "......OOOOOOOOOOOO......",
    "........................",
    "........................",
]

TOMATO = [
    "........................",
    "........................",
    "..........OOOO..........",
    "......OOOONGGNOOOO......",
    ".....ONGGGGGGGGGGNO.....",
    "....ONGGONGGGGNOGGNO....",
    "...OORRONGGGGGGNORROO...",
    "..ORRRRRRRRRRRRRRRRDDO..",
    ".ORRRRRRRRRRRRRRRRDDDDO.",
    ".ORRWWRRRRRRRRRRRDWWDDO.",
    "ORRWWRRRRRRRRRRRDDDWWDDO",
    "ORRRRRRRRRRRRRRDDDDDDDDO",
    "ORRRRRRRRRRRRRDDDDDDDDDO",
    "ORRRRRRRRRRRRDDDDDDDDDDO",
    "ORRRRRRRRRRRDDDDDDDDDDDO",
    ".ORRRRRRRRRDDDDDDDDDDDO.",
    ".ORRRRRRRRDDDDDDDDDDDDO.",
    "..ORRRRRRDDDDDDDDDDDDO..",
    "..ORRRRRDDDDDDDDDDDDDO..",
    "...OORRDDDDDDDDDDDDOO...",
    ".....OODDDDDDDDDDOO.....",
    ".......OOOOOOOOOO.......",
    "........................",
    "........................",
]

CARROT = [
    "........................",
    "......OO.OOOOOO.OO......",
    ".....ONNOONNNNOONNO.....",
    ".....ONNONNNNNNONNO.....",
    "......ONNONNNNONNO......",
    "......OONNNNNNNNOO......",
    "........OOAAAAOO........",
    ".......OAAAAAAAAO.......",
    ".......OAAAAAAAAO.......",
    "......OAAKAAAAKAAO......",
    "......OAAAAAAAAAAO......",
    "......OAAAAAAAAAAO......",
    ".......OAKAAAAKAO.......",
    ".......OAAAAAAAAO.......",
    ".......OAAAAAAAAO.......",
    "........OAKAAKAO........",
    "........OAAAAAAO........",
    "........OAAAAAAO........",
    ".........OAAAAO.........",
    ".........OAAAAO.........",
    ".........OAAAAO.........",
    "..........OAAO..........",
    "..........OOOO..........",
    "........................",
]

BROCCOLI = [
    "........................",
    "......OOOOOOOOOOOO......",
    "....OONNNNNNNNNNNNOO....",
    "...ONNGGNNGGGGNNGGNNO...",
    "..ONNGGNNGGGGGGNNGGNNO..",
    "..ONGGNNGGGGGGGGNNGGNO..",
    ".ONGGNNGGGGGGGGGGNNGGNO.",
    ".ONNGGGGNNGGGGNNGGGGNNO.",
    "ONGGNNGGGGGGGGGGGGNNGGNO",
    "ONGGGGNNGGGGGGGGNNGGGGNO",
    "ONNGGGGGGNNGGNNGGGGGGNNO",
    ".ONNGGNNGGGGGGGGNNGGNNO.",
    "..OONNGGGGGGGGGGGGNNOO..",
    "....OOONNGGGGGGNNOOO....",
    ".......OOSSSSSSOO.......",
    ".......OSSSSSSSSO.......",
    "........OSSSSSSO........",
    "........OSSSSSSO........",
    "........OSSSSSSO........",
    "........OSSSSSSO........",
    ".........OSSSSO.........",
    ".........OSSSSO.........",
    "..........OOOO..........",
    "........................",
]

CORN = [
    "........................",
    "..........OOOO..........",
    ".......OOONGGNOOO.......",
    "......ONNNOGGONNNO......",
    ".....ONNGGGGGGGGNNO.....",
    "....ONNGGYYYYYYGGNNO....",
    "...ONGGYYSYYYYSYYGGNO...",
    "...ONGGYSYYSSYYSYGGNO...",
    "..ONGGYYSYYSSYYSYYGGNO..",
    "..ONGGYSYYSYYSYYSYGGNO..",
    "..ONGYYSYYSYYSYYSYYGNO..",
    "..ONGYSYYSYYYYSYYSYGNO..",
    "..ONGYYSYYSYYSYYSYYGNO..",
    "..ONGYSYYSYYYYSYYSYGNO..",
    "..ONGGYYSYYSSYYSYYGGNO..",
    "...ONGGYSYYSSYYSYGGNO...",
    "...ONGGYYSYYYYSYYGGNO...",
    "....ONGGYYSYYSYYGGNO....",
    "....ONNGGYYYYYYGGNNO....",
    ".....OONGGGGGGGGNOO.....",
    ".......OONNGGNNOO.......",
    ".........OOOOOO.........",
    "........................",
    "........................",
]

EGGPLANT = [
    "........................",
    "..........OOOO..........",
    "........OONGGNOO........",
    "......OONGGGGGGNOO......",
    ".....ONGGGONNOGGGNO.....",
    ".....ONGGONVVNOGGNO.....",
    "....OOVVVVVVVVVVVVOO....",
    "...OVVVVVVVVVVVVVVVJO...",
    "..OVVVVVVVVVVVVVVVJJJO..",
    "..OVVWVVVVVVVVVVVJWJJO..",
    ".OVVWVVVVVVVVVVVJJJWJJO.",
    ".OVVVVVVVVVVVVVJJJJJJJO.",
    ".OVVVVVVVVVVVVJJJJJJJJO.",
    ".OVVVVVVVVVVVJJJJJJJJJO.",
    ".OVVVVVVVVVVJJJJJJJJJJO.",
    ".OVVVVVVVVVJJJJJJJJJJJO.",
    "..OVVVVVVVJJJJJJJJJJJO..",
    "..OVVVVVVJJJJJJJJJJJJO..",
    "...OVVVVJJJJJJJJJJJJO...",
    "....OVVJJJJJJJJJJJJO....",
    ".....OOJJJJJJJJJJOO.....",
    ".......OOOOOOOOOO.......",
    "........................",
    "........................",
]

PUMPKIN = [
    "........................",
    "........................",
    "..........OOOO..........",
    ".........ONNNNO.........",
    "........ONNGGNNO........",
    "......OOONGGGGNOOO......",
    "....OOAAAOOOOOOAAAOO....",
    "...OAAAAAAAAAAAAAAAAO...",
    "..OAAAAAOAAAAAAOAAAAAO..",
    ".OAAAAAAOAAAAAAOAAAAAAO.",
    ".OAAAAAAOAAAAAAOAAAAAAO.",
    "OAAAAAAAOAAAAAAOAAAAAAAO",
    "OAAKKAAAOAAAAAAOAAAKKAAO",
    "OAKKKAAAOAKKKKAOAAAKKKAO",
    "OKKKKKKKOKKKKKKOKKKKKKKO",
    ".OKKKKKKOKKKKKKOKKKKKKO.",
    ".OKKKKKKOKKKKKKOKKKKKKO.",
    "..OKKKKKOKKKKKKOKKKKKO..",
    "..OKKKKKOKKKKKKOKKKKKO..",
    "...OOKKKKOKKKKOKKKKOO...",
    ".....OOKKKOKKOKKKOO.....",
    ".......OOOOOOOOOO.......",
    "........................",
    "........................",
]

CHILLI = [
    "........................",
    "........................",
    "..........OOO...........",
    ".........ONNNO..........",
    ".........ONNNO..........",
    "........OONNOO..........",
    ".......ONNNOO...........",
    "......OONNO.............",
    ".....ORRRO..............",
    "....ORRRRO..............",
    "....ORRRRRO.............",
    "....ORRRRRRO............",
    "....ORDRRRRRO...........",
    "....ORDDRRRRRO..........",
    "....ORDDDRRRRRO.........",
    ".....ODDDDRRRRRO........",
    ".....ODDDDDRRRRRO.......",
    "......ODDDDDRRRRO.......",
    ".......ODDDDDRRRO.......",
    "........ODDDDDRRO.......",
    ".........OODDDRRO.......",
    "...........OODDOO.......",
    ".............OO.........",
    "........................",
]

ONION = [
    "........................",
    "..........OOOO..........",
    "........OONGGNOO........",
    ".......ONGGGGGGNO.......",
    "......ONGGONNOGGNO......",
    "......ONGONVVNOGNO......",
    ".....OOVVVVVVVVVVOO.....",
    "....OVVVVVVVVVVVVVVO....",
    "...OVVVOVVVVVVVVOVVVO...",
    "..OVPVOVVVVVVVVVVOVPVO..",
    "..OVPVOVVVOVVOVVVOVPVO..",
    ".OVPVOVPVOVVVVOVPVOVPVO.",
    ".OVPVOVPVOVPPVOVPVOVPVO.",
    ".OVPVOVPVOVPPVOVPVOVPVO.",
    ".OVPPVOVPVOPPOVPVOVPPVO.",
    ".OVPPVOVPVOPPOVPVOVPPVO.",
    "..OVPPVOVPVPPVPVOVPPVO..",
    "..OVVPPVOVPPPPVOVPPVVO..",
    "...OVVPPVVPPPPVVPPVVO...",
    "....OVVVVVVVVVVVVVVO....",
    ".....OOVVVVVVVVVVOO.....",
    ".......OOOOOOOOOO.......",
    "........................",
    "........................",
]

FRUIT = {
    "apple": APPLE,
    "pear": PEAR,
    "banana": BANANA,
    "orange": ORANGE,
    "lemon": LEMON,
    "strawberry": STRAWBERRY,
    "grapes": GRAPES,
    "watermelon": WATERMELON,
    "pineapple": PINEAPPLE,
    "peach": PEACH,
    "kiwi": KIWI,
    "avocado": AVOCADO,
    "tomato": TOMATO,
    "carrot": CARROT,
    "broccoli": BROCCOLI,
    "corn": CORN,
    "eggplant": EGGPLANT,
    "pumpkin": PUMPKIN,
    "chilli": CHILLI,
    "onion": ONION,
}

# --------------------------------------------------------------------------- the street

CAR = [
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........OOOOOOOO........",
    ".......OBBBBBBBBO.......",
    "......OBCCCCOCCCCO......",
    ".....OBBCCCCOCCCCBO.....",
    "....OBBBBBBBBBBBBBBO....",
    "...OBBBBBBBBBBBBBBBBO...",
    "..OBBBBBBBBBBBBBBBBBBO..",
    "..OBBBBBBBBBBBBBBBBBBO..",
    "..OUUUUUUUUUUUUUUUUUUO..",
    "..OUUUUUUUUUUUUUUUUUUO..",
    "..OOOOXXOOOOOOOOXXOOOO..",
    "....OXXXXO....OXXXXO....",
    "....OXLLXO....OXLLXO....",
    "....OXXXXO....OXXXXO....",
    ".....OOOO......OOOO.....",
    "........................",
    "........................",
    "........................",
]

TAXI = [
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........OOOOOOOO........",
    ".......OYYYYYYYYO.......",
    "......OYCCCCOCCCCO......",
    ".....OYYCCCCOCCCCYO.....",
    "....OYYYYYYYYYYYYYYO....",
    "...OYYYYYYYYYYYYYYYYO...",
    "..OYYYYYYYYYYYYYYYYYYO..",
    "..OYYYYYYYYYYYYYYYYYYO..",
    "..OXXXXXXXXXXXXXXXXXXO..",
    "..OXXXXXXXXXXXXXXXXXXO..",
    "..OOOOXXOOOOOOOOXXOOOO..",
    "....OXXXXO....OXXXXO....",
    "....OXLLXO....OXLLXO....",
    "....OXXXXO....OXXXXO....",
    ".....OOOO......OOOO.....",
    "........................",
    "........................",
    "........................",
]

BUS = [
    "........................",
    "........................",
    "...OOOOOOOOOOOOOOOOOO...",
    "..OAAAAAAAAAAAAAAAAAAO..",
    "..OACCOCCOCCOCCOCCOCCAO.",
    "..OACCOCCOCCOCCOCCOCCAO.",
    "..OAAAAAAAAAAAAAAAAAAAO.",
    "..OAAAAAAAAAAAAAAAAAAAO.",
    "..OACCOCCOCCOCCOCCOCCAO.",
    "..OACCOCCOCCOCCOCCOCCAO.",
    "..OAAAAAAAAAAAAAAAAAAAO.",
    "..OKKKKKKKKKKKKKKKKKKKO.",
    "..OKKKKKKKKKKKKKKKKKKKO.",
    "..OKKKKKKKKKKKKKKKKKKKO.",
    "..OKKKKKKKKKKKKKKKKKKKO.",
    "..OOOXXOOOOOOOOOOXXOOOO.",
    "....OXXXXO......OXXXXO..",
    "....OXLLXO......OXLLXO..",
    "....OXXXXO......OXXXXO..",
    ".....OOOO........OOOO...",
    "........................",
    "........................",
    "........................",
    "........................",
]

TRUCK = [
    "........................",
    "........................",
    "........................",
    ".........OOOOOOOOOOOOO..",
    "........OLLLLLLLLLLLLLO.",
    "........OLLLLLLLLLLLLLO.",
    "...OOOOOOLLLLLLLLLLLLLO.",
    "..OBBBBBOLLLLLLLLLLLLLO.",
    "..OBCCCBOLLLLLLLLLLLLLO.",
    "..OBCCCBOLLLLLLLLLLLLLO.",
    "..OBBBBBOLLLLLLLLLLLLLO.",
    ".OBBBBBBOLLLLLLLLLLLLLO.",
    ".OBBBBBBOMMMMMMMMMMMMMO.",
    ".OUUUUUUOMMMMMMMMMMMMMO.",
    ".OUUUUUUOMMMMMMMMMMMMMO.",
    ".OOXXOOOOOOXXOOOOOXXOOO.",
    "..OXXXXO..OXXXXO.OXXXXO.",
    "..OXLLXO..OXLLXO.OXLLXO.",
    "..OXXXXO..OXXXXO.OXXXXO.",
    "...OOOO....OOOO...OOOO..",
    "........................",
    "........................",
    "........................",
    "........................",
]

TRAIN = [
    "........................",
    "........................",
    "......OOOO..............",
    "......OXXO..............",
    "......OXXOOOOOOOOOOO....",
    ".....OOOOUUUUUUUUUUUO...",
    "....OUUUUUUUUUUUUUUUO...",
    "....OUUUUUUUUUUUUUUUO...",
    "....OUCCOCCOUUOCCOCCO...",
    "....OUCCOCCOUUOCCOCCO...",
    "....OUUUUUUUUUUUUUUUO...",
    "...OUUUUUUUUUUUUUUUUUO..",
    "...ORRRRRRRRRRRRRRRRRO..",
    "...ORRRRRRRRRRRRRRRRRO..",
    "...OOXXOOOXXOOOXXOOXXOO.",
    "...OXXXXOOXXXXOOXXXXXO..",
    "...OXLLXOOXLLXOOXLLLXO..",
    "...OXXXXOOXXXXOOXXXXXO..",
    "....OOOO..OOOO..OOOOO...",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
]

TRAM = [
    "........................",
    "..........OO............",
    "..........OO............",
    "....OOOOOOOOOOOOOOOO....",
    "...OGGGGGGGGGGGGGGGGO...",
    "...OGCCCOCCCOCCCOCCGO...",
    "...OGCCCOCCCOCCCOCCGO...",
    "...OGCCCOCCCOCCCOCCGO...",
    "...OGGGGGGGGGGGGGGGGO...",
    "...OGGGGGGGGGGGGGGGGO...",
    "...ONNNNNNNNNNNNNNNNO...",
    "...ONNNOCCCONNNOCCCNO...",
    "...ONNNOCCCONNNOCCCNO...",
    "...ONNNNNNNNNNNNNNNNO...",
    "...OYYYYYYYYYYYYYYYYO...",
    "...OOXXOOOOOOOOOOXXOOO..",
    "....OXXXXO.....OXXXXO...",
    "....OXLLXO.....OXLLXO...",
    "....OXXXXO.....OXXXXO...",
    ".....OOOO.......OOOO....",
    "........................",
    "........................",
    "........................",
    "........................",
]

FIRE_ENGINE = [
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........OOOOOOOO........",
    ".......ORRRRRRRRO.......",
    "......ORCCCCOCCCCO......",
    ".....ORRCCCCOCCCCRO.....",
    "....ORRRRRRRRRRRRRRO....",
    "...ORRRRRRRRRRRRRRRRO...",
    "..ORRRRRRRRRRRRRRRRRRO..",
    "..ORRRRRRRRRRRRRRRRRRO..",
    "..ODDDDDDDDDDDDDDDDDDO..",
    "..ODDDDDDDDDDDDDDDDDDO..",
    "..OOOOXXOOOOOOOOXXOOOO..",
    "....OXXXXO....OXXXXO....",
    "....OXLLXO....OXLLXO....",
    "....OXXXXO....OXXXXO....",
    ".....OOOO......OOOO.....",
    "........................",
    "........................",
    "........................",
]

AMBULANCE = [
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........OOOOOOOO........",
    ".......OWWWWWWWWO.......",
    "......OWCCCCOCCCCO......",
    ".....OWWCCCCOCCCCWO.....",
    "....OWWWWWWWWWWWWWWO....",
    "...OWWWWWWRRWWWWWWWWO...",
    "..OWWWWWWRRRRWWWWWWWWO..",
    "..OWWWWWWRRRRWWWWWWWWO..",
    "..ORRRRRRRRRRRRRRRRRRO..",
    "..ORRRRRRRRRRRRRRRRRRO..",
    "..OOOOXXOOOOOOOOXXOOOO..",
    "....OXXXXO....OXXXXO....",
    "....OXLLXO....OXLLXO....",
    "....OXXXXO....OXXXXO....",
    ".....OOOO......OOOO.....",
    "........................",
    "........................",
    "........................",
]

POLICE_CAR = [
    "........................",
    "........................",
    "........................",
    "........................",
    ".........OOOOOO.........",
    ".........OBBRRO.........",
    "........OOOOOOOO........",
    ".......OWWWWWWWWO.......",
    "......OWCCCCOCCCCO......",
    ".....OWWCCCCOCCCCWO.....",
    "....OWWWWWWWWWWWWWWO....",
    "...OWWWWWWWWWWWWWWWWO...",
    "..OWWWWWWWWWWWWWWWWWWO..",
    "..OWWWWWWWWWWWWWWWWWWO..",
    "..OUUUUUUUUUUUUUUUUUUO..",
    "..OUUUUUUUUUUUUUUUUUUO..",
    "..OOOOXXOOOOOOOOXXOOOO..",
    "....OXXXXO....OXXXXO....",
    "....OXLLXO....OXLLXO....",
    "....OXXXXO....OXXXXO....",
    ".....OOOO......OOOO.....",
    "........................",
    "........................",
    "........................",
]

BICYCLE = [
    "........................",
    "........................",
    "........................",
    "........................",
    ".............OOOOOOO....",
    "............OLLLLLLRO...",
    "......OOOOO.OLLLLLLLO...",
    ".....OXXXXXO.OOOLOOO....",
    ".....OXXXXXO...OLO......",
    "...OOOOOLOOOOOOOLOOOO...",
    "..OXXXXXLLLLLLLLLXXXXO..",
    ".OXXXXXXLOOOOOOXLXXXXXO.",
    "OXXXOOOXLXO.OOXLLLOOXXXO",
    "XXXO.O.OLXXOLLLXLOOOOXXX",
    "XXO.OLOOLLLLOXXOLLLLOOXX",
    "XXO.OLLLLXXOOXXOLLLLOOXX",
    "XXO.OLOOOXXOOXXOOLLLOOXX",
    "XXXO.O.OXXXOOXXXOOOOOXXX",
    "OXXXOOOXXXO..OXXXOOOXXXO",
    ".OXXXXXXXO....OXXXXXXXO.",
    "..OXXXXXO......OXXXXXO..",
    "...OOOOO........OOOOO...",
    "........................",
    "........................",
]

MOTORBIKE = [
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    ".............OOOOOOO....",
    "............OXXXXXXXO...",
    ".............OORRRRO....",
    "........OOOOOOORLLRO....",
    ".......OXXXXRRRRLLO.....",
    ".......OXXXXRRRRLLO.....",
    "...OOOOORRRRRRRRLLOOO...",
    "..OXXXRRRRRRRRRRLLXXXO..",
    ".OXXXXRRRRRRRRRRRRXXXXO.",
    "OXXXOORRRRRRRRRRRROOXXXO",
    "OXXO.OXXXXRRRRRRRRO.OXXO",
    "OXXOOLXXXXOOOOXXOOLOOXXO",
    "OXXO.OOOXXO..OXXO.O.OXXO",
    "OXXXOOOXXXO..OXXXOOOXXXO",
    ".OXXXXXXXO....OXXXXXXXO.",
    "..OXXXXXO......OXXXXXO..",
    "...OOOOO........OOOOO...",
    "........................",
    "........................",
]

TRAFFIC_LIGHT = [
    "........................",
    "......OOOOOOOOOOOO......",
    ".....OXXXXXXXXXXXXO.....",
    "....OXXXXXXXXXXXXXXO....",
    "....OXXOOOOOOOOOOXXO....",
    "....OXORRRRRRRRRROXO....",
    "....OXORRRRRRRRRROXO....",
    "....OXORRRRRRRRRROXO....",
    "....OXOOOOOOOOOOOOXO....",
    "....OXOYYYYYYYYYYOXO....",
    "....OXOYYYYYYYYYYOXO....",
    "....OXOYYYYYYYYYYOXO....",
    "....OXOOOOOOOOOOOOXO....",
    "....OXOGGGGGGGGGGOXO....",
    "....OXOGGGGGGGGGGOXO....",
    "....OXOGGGGGGGGGGOXO....",
    "....OXXOOOOOOOOOOXXO....",
    "....OXXXXXXXXXXXXXXO....",
    ".....OXXXXXXXXXXXXO.....",
    "......OOOMMMMMMOOO......",
    ".......OMMMMMMMMO.......",
    ".......OMMMMMMMMO.......",
    "......OMMMMMMMMMMO......",
    "......OOOOOOOOOOOO......",
]

NO_ENTRY = [
    "........................",
    "........................",
    "........OOOOOOOO........",
    "......OORRRRRRRROO......",
    ".....ORRRRRRRRRRRRO.....",
    "....ORRRRRRRRRRRRRRO....",
    "...ORRRRRRRRRRRRRRRRO...",
    "..ORRRRRRRRRRRRRRRRRRO..",
    "..ORWWWWWWWWWWWWWWWWRO..",
    "..ORWWWWWWWWWWWWWWWWRO..",
    "..OWWWWWWWWWWWWWWWWWWO..",
    "..OWWWWWWWWWWWWWWWWWWO..",
    "..ORWWWWWWWWWWWWWWWWRO..",
    "..ORWWWWWWWWWWWWWWWWRO..",
    "..ORRRRRRRRRRRRRRRRRRO..",
    "..ORRRRRRRRRRRRRRRRRRO..",
    "...ORRRRRRRRRRRRRRRRO...",
    "....ORRRRRRRRRRRRRRO....",
    ".....ORRRRRRRRRRRRO.....",
    "......OOOMMMMMMOOO......",
    ".........OMMMMO.........",
    ".........OMMMMO.........",
    ".........OMMMMO.........",
    ".........OOOOOO.........",
]

CONE = [
    "........................",
    "........................",
    "..........OOOO..........",
    ".........OAAAAO.........",
    ".........OAAAAO.........",
    "........OAAAAAAO........",
    "........OAAAAAAO........",
    ".......OWWWWWWWWO.......",
    ".......OWWWWWWWWO.......",
    "......OAAAAAAAAAAO......",
    "......OAAAAAAAAAAO......",
    ".....OAAAAAAAAAAAAO.....",
    ".....OWWWWWWWWWWWWO.....",
    "....OWWWWWWWWWWWWWWO....",
    "....OAAAAAAAAAAAAAAO....",
    "...OAAAAAAAAAAAAAAAAO...",
    "...OAAAAAAAAAAAAAAAAO...",
    "..OAAAAAAAAAAAAAAAAAAO..",
    "..OWWWWWWWWWWWWWWWWWWO..",
    ".OWWWWWWWWWWWWWWWWWWWWO.",
    ".OXXXXXXXXXXXXXXXXXXXXO.",
    ".OXXXXXXXXXXXXXXXXXXXXO.",
    ".OOOOOOOOOOOOOOOOOOOOOO.",
    "........................",
]

STREET_LAMP = [
    "........................",
    "........................",
    "........................",
    "...........OOOOOOOOO....",
    "..........OXXXMMMMMMO...",
    "..........OXXXMMMMMMOO..",
    "..........OMMMMMXXXXXXO.",
    "..........OOOOOOXXXXXXO.",
    ".........OMMMMO.OYYYYO..",
    ".........OMMMMO.OYYYYO..",
    ".........OMMMMO..OYYO...",
    ".........OMMMMO..OYYO...",
    ".........OMMMMO...OO....",
    ".........OMMMMO.........",
    ".........OMMMMO.........",
    ".........OMMMMO.........",
    ".........OMMMMO.........",
    ".........OMMMMO.........",
    ".........OMMMMO.........",
    ".........OMMMMO.........",
    ".......OOOMMMMOOO.......",
    "......OMMMMMMMMMMO......",
    "......OMMMMMMMMMMO......",
    ".......OOOOOOOOOO.......",
]

HYDRANT = [
    "...........O............",
    "..........OROO..........",
    ".........ORRRRO.........",
    "........ORRRRRO.........",
    "........ORRRRROO........",
    ".......ORRRRRRRRO.......",
    ".......ORRRRRRRRO.......",
    ".......ODDDDDDDDO.......",
    ".....OOODDDDDDDDOOO.....",
    "....OLLLRRRRRRRRLLLO....",
    "....OLLLRRRRRRRRLLLO....",
    "....OLLLRRRRRRRRLLLO....",
    "....OLLLRRRRRRRRLLLO....",
    ".....OOORRRRRRRROOO.....",
    ".......ODDDDDDDDO.......",
    ".......ODDDDDDDDO.......",
    ".......ORRRRRRRRO.......",
    ".......ORRRRRRRRO.......",
    ".......ORRRRRRRRO.......",
    "......OORRRRRRRROO......",
    ".....OLLLLLLLLLLLLO.....",
    ".....OLLLLLLLLLLLLO.....",
    ".....OLLLLLLLLLLLLO.....",
    "......OOOOOOOOOOOO......",
]

DIGGER = [
    "........................",
    "........................",
    "...............OOO......",
    "..............OYYO......",
    ".....OOOOO...OYYO.......",
    "....OYYYYYO.OYYO........",
    "....OYCCCYOOYYO.........",
    "....OYCCCYOYYO..........",
    "....OYYYYYOYO...........",
    "...OYYYYYYYO............",
    "...OYYYYYYYOOOO.........",
    "...OYYYYYYYYYYYO........",
    "..OYYYYYYYYYYYYYO.......",
    "..OAAAAAAAAAAAAAO..OOO..",
    "..OAAAAAAAAAAAAAOOOLLLO.",
    "..OOOOOOOOOOOOOOOLLLLLO.",
    "..OXXXXXXXXXXXXXOLLLLO..",
    ".OXXOOXXOOXXOOXXXOOOOO..",
    ".OXXXXXXXXXXXXXXXO......",
    ".OOXXOOXXOOXXOOXXO......",
    "..OOOOOOOOOOOOOOO.......",
    "........................",
    "........................",
    "........................",
]

CRANE = [
    "........................",
    "........................",
    "........................",
    "..OOOOOOOOOOOOOOOOOOOO..",
    ".OYYYYYYYYYYYYYYYYYYYYO.",
    ".OYYOOYYOOYYYYYOOYYOOYO.",
    ".OYYYYYYYYYYYYYYYYYYYYO.",
    "..OOOLLOOOYOOYOOOOXXXXO.",
    "....OLLO.OYYYYO..OXXXXO.",
    "....OLLO.OYOOYO..OXXXXO.",
    "....OLLO.OYYYYO...OOOO..",
    "....OLLO.OYOOYO.........",
    "...OLLLLOOYYYYO.........",
    "...OLLLLOOYOOYO.........",
    "...OLLLLOOYYYYO.........",
    "...OLLLLOOYOOYO.........",
    "....OOOO.OYYYYO.........",
    ".........OYOOYO.........",
    ".........OYYYYO.........",
    ".......OOOYOOYOOO.......",
    "......OXXXXXXXXXXO......",
    "......OXXXXXXXXXXO......",
    "......OXXXXXXXXXXO......",
    ".......OOOOOOOOOO.......",
]

SKYSCRAPER = [
    "........................",
    "..........OOOO..........",
    "..........OLLO..........",
    ".......OOOOLLOOOO.......",
    ".......OMMMLLMMMO.......",
    ".......OMMMLLMMMO.......",
    "....OOOOMMMLLMMMOOOO....",
    "....OMCCOMCCCCMOCCMO....",
    "....OMCCOMCCCCMOCCMO....",
    "....OMMMOMMMMMMOMMMO....",
    "....OMCCOMCCCCMOCCMO....",
    "....OMCCOMCCCCMOCCMO....",
    "....OMMMOMMMMMMOMMMO....",
    "....OMCCOMCCCCMOCCMO....",
    "....OMCCOMCCCCMOCCMO....",
    "....OMMMOMMMMMMOMMMO....",
    "....OMCCOMCCCCMOCCMO....",
    "....OMCCOMCCCCMOCCMO....",
    "....OMMMOMMMMMMOMMMO....",
    "....OLCCOLCCCCLOCCLO....",
    "....OLCCOLCCCCLOCCLO....",
    "....OLLLOLLLLLLOLLLO....",
    "....OLLLOLLLLLLOLLLO....",
    "....OOOOOOOOOOOOOOOO....",
]

FUEL_PUMP = [
    "........................",
    "........................",
    "......OOOOOOOOOOOO......",
    ".....ORRRRRRRRRRRRO.....",
    ".....ORRRRRRRRRRRRO.....",
    ".....OROOOOOOOOOORO.....",
    ".....OROWWWWWWWWORO.....",
    ".....OROWWWWWWWWORO.....",
    ".....OROOOOOOOOOORO.....",
    ".....ORRRRRRRRRRRRO.....",
    "OOO..ORRRRRRRRRRRRO..OOO",
    "OXO..ORRRRRRRRRRRRO..OXO",
    "OXOOOORRRRRRRRRRRROOOOXO",
    "OXXXXORDDDDDDDDDDROXXXXO",
    "OOOOXORDDDDDDDDDDROXOOOO",
    "....XORDDDDDDDDDDROX....",
    "....XORDDDDDDDDDDROX....",
    "....XORDDDDDDDDDDROX....",
    "....OORDDDDDDDDDDROO....",
    "......ODDDDDDDDDDO......",
    "......ODDDDDDDDDDO......",
    "......OLLLLLLLLLLO......",
    "......OLLLLLLLLLLO......",
    "......OOOOOOOOOOOO......",
]

CITY = {
    "car": CAR,
    "taxi": TAXI,
    "bus": BUS,
    "truck": TRUCK,
    "train": TRAIN,
    "tram": TRAM,
    "fire_engine": FIRE_ENGINE,
    "ambulance": AMBULANCE,
    "police_car": POLICE_CAR,
    "bicycle": BICYCLE,
    "motorbike": MOTORBIKE,
    "traffic_light": TRAFFIC_LIGHT,
    "no_entry": NO_ENTRY,
    "cone": CONE,
    "street_lamp": STREET_LAMP,
    "hydrant": HYDRANT,
    "digger": DIGGER,
    "crane": CRANE,
    "skyscraper": SKYSCRAPER,
    "fuel_pump": FUEL_PUMP,
}

# --------------------------------------------------------------------------- the critters

SLIME = [
    "........................",
    "........................",
    "........................",
    "..........OOOO..........",
    ".......OOOIIIIOOO.......",
    ".....OOIIIIIIIIIIOO.....",
    "....OIIIIIIIIIIIIIIO....",
    "...OIIIIIIIIIIIIIIIIO...",
    "..OIIIIIIIIIIIIIIIIGGO..",
    "..OIIIIIIIIIIIIIIIGGGO..",
    ".OIIIIIIIIIIIIIIIGGGGGO.",
    ".OIIOOIIIIIIIIIIGGOOGGO.",
    ".OIIOOIIIIIIIIIGGGOOGGO.",
    ".OIIIIIIIIIIIIGGGGGGGGO.",
    ".OIIIIIIOOOOOOOOGGGGGGO.",
    "OIIIIIIIIIIIGGGGGGGGGGGO",
    "OIIIIIIIIIIGGGGGGGGGGGGO",
    "OGGGGGGGGGGGGGGGGGGGGGGO",
    "OGGGGGGGGGGGGGGGGGGGGGGO",
    "OGGGGGGGGGGGGGGGGGGGGGGO",
    ".OGGGGGGGGGGGGGGGGGGGGO.",
    ".OOOOOOOOOOOOOOOOOOOOOO.",
    "........................",
    "........................",
]

CHICK = [
    "........................",
    "........................",
    "..........OOOO..........",
    ".......OOOYYYYOOO.......",
    "......OYYYYYYYYYYO......",
    ".....OYYYYYYYYYYYYO.....",
    "....OYYYYYYYYYYYYYYO....",
    "....OYYYYYYYYYYYYYYO....",
    "...OYYOOYYYYYYYYOOYSO...",
    "...OYYOOYYYYYYYYOOSSO...",
    "...OYYYYYYYYYYYYYSSSO...",
    "...OYYYYYOAAAAOYSSSSO...",
    "....OYYYYOAAAAOSSSSO....",
    "....OYYYYYYYYYSSSSSO....",
    "...OYSSYYYYYYSSSSSSSO...",
    "..OYSSSYYYYYSSSSSSSSSO..",
    "..OYSSSYYYYSSSSSSSSSSO..",
    "..OYSSYYYYSSSSSSSSSSSO..",
    "..OYYYYYYSSSSSSSSSSSSO..",
    "...OYYYYSSSSSSSSSSSSO...",
    "....OOOAAOOOOOOAAOOO....",
    "......OAAOAAAAOAAO......",
    "......OOOOOOOOOOOO......",
    "........................",
]

KITTEN = [
    "........................",
    "...OO..............OO...",
    "..OLLO............OLLO..",
    "..OLPLO..........OLPLO..",
    "..OLPLLOOOOOOOOOOLLPLO..",
    "..OLLLLLLLLLLLLLLLLLLO..",
    ".OLLLLLLLLLLLLLLLLLLLMO.",
    ".OLLLLLLLLLLLLLLLLLLMMO.",
    ".OLLWWLLLLLLLLLLLLWWMMO.",
    ".OLLWOLLLLLLLLLLLLOWMMO.",
    ".OLLLLLLLLLLLLLLLMMMMMO.",
    ".OLLLLLLLOPPPPOLMMMMMMO.",
    ".OLLLLLLOPPPPPPOMMMMMMO.",
    "..OLLLLLOWWWWWWOMMMMMO..",
    "..OLLLLLLWWWWWWMMMMMMO..",
    "...OLLLLLLLLMMMMMMMMO...",
    "....OLLLLLLMMMMMMMMO....",
    "....OLLLLLMMMMMMMMMO....",
    "...OLLLLLMMMMMMMMMMMO...",
    "..OLLLLLMMMMMMMMMMMMMO..",
    "..OLLLLMMMMMMMMMMMMMMO..",
    "..OMMOOMMOOMMOOMMOOMMO..",
    "..OOOO.OOOOOOOOOO.OOOO..",
    "........................",
]

BUNNY = [
    "........................",
    "....OO............OO....",
    "...OWPO..........OPWO...",
    "...OWPO..........OPWO...",
    "...OWPO.OO....OO.OPWO...",
    "...OWPOOWPO..OPWOOPWO...",
    "...OWWOOWPO..OPWOOWWO...",
    "....OWWOWWO..OWWOWWO....",
    "....OWWWWWO..OWWWWWO....",
    "...OWWWWWWWWWWWWWWLLO...",
    "..OWWWWWWWWWWWWWWLLLLO..",
    "..OWWOOWWWWWWWWWLOOLLO..",
    "..OWWOOWWWWWWWWLLOOLLO..",
    "..OWWWWWWWOPPOLLLLLLLO..",
    "..OWWWWWWOPPPPOLLLLLLO..",
    "...OWWWWWOWWLLOLLLLLO...",
    "....OWWWWWWLLLLLLLLO....",
    "...OWWWWWWLLLLLLLLLLO...",
    "..OWWWWWWLLLLLLLLLLLLO..",
    "..OWWWWWLLLLLLLLLLLLLO..",
    "..OWWWWLLLLLLLLLLLLLLO..",
    "...OWWLLLLLLLLLLLLLLO...",
    "....OOOOOOOOOOOOOOOO....",
    "........................",
]

FOX = [
    "........................",
    "..OO................OO..",
    ".OAAO..............OAAO.",
    ".OAKAO............OAKAO.",
    ".OAAAAOOOOOOOOOOOOAAAAO.",
    "..OAAAAAAAAAAAAAAAAAAO..",
    "..OAAAAAAAAAAAAAAAAAAO..",
    ".OAAAAAAAAAAAAAAAAAAAAO.",
    ".OAAOOAAAAAAAAAAAAOOAKO.",
    ".OAAOOAAAAAAAAAAAAOOKKO.",
    ".OAAAAAAAAAAAAAAAAAKKKO.",
    "..OAAAAAAAAAAAAAAAKKKO..",
    "..OAAAAAAWWWWWWAAKKKKO..",
    "...OAAAAWWWWWWWWKKKKO...",
    "...OAAAAWWOOOOWWKKKKO...",
    "....OAAAWWWWWWWWKKKO....",
    "....OAAAAWWWWWWKKKKO....",
    "...OAAAAAAAAKKKKKKKKO...",
    "..OAAAAAAAAKKKKKKKKKKO..",
    "..OAAAAAAAKKKKKKKKKKKO..",
    "..OAAWWWWWWWWWWWWWWKKO..",
    "...OAAWWWWWWWWWWWWKKO...",
    "...OOOOOOOOOOOOOOOOOO...",
    "........................",
]

DRAGON = [
    "........................",
    ".....OO...OOOO...OO.....",
    "....OYYO.OYYYYO.OYYO....",
    "....OYYOOYYYYYYOOYYO....",
    ".....OOGGGGGGGGGGOO.....",
    "...OOGGGGGGGGGGGGGGOO...",
    "..OGGGGGGGGGGGGGGGGGGO..",
    "..OGGGGGGGGGGGGGGGGGNO..",
    ".OGGOOGGGGGGGGGGGGOONNO.",
    ".OGGOOGGGGGGGGGGGGOONNO.",
    ".OGGGGGGGGGGGGGGGNNNNNO.",
    ".OGGGGGGGOOOOOOGNNNNNNO.",
    "..OGGGGGGGGGGGGNNNNNNO..",
    "..OGGGGGGGGGGGNNNNNNNO..",
    "OOGGGGGGYYYYYYYYNNNNNNOO",
    "ONNGGGGGYYYYYYYYNNNNNNNO",
    "ONNNGGGGYYYYYYYYNNNNNNNO",
    "ONNNNGGGYYYYYYYYNNNNNNNO",
    "OONNNGGGGYYYYYYNNNNNNNOO",
    "..OONGGGNNYYYYNNNNNNOO..",
    "....OGGNNNNNNNNNNNNO....",
    "....OGNOONNNNNNOONNO....",
    "....OOO..OOOOOO..OOO....",
    "........................",
]

GHOST = [
    "........................",
    "........................",
    "..........OOOO..........",
    ".......OOOWWWWOOO.......",
    ".....OOWWWWWWWWWWOO.....",
    "....OWWWWWWWWWWWWWWO....",
    "...OWWWWWWWWWWWWWWWWO...",
    "..OWWWWWWWWWWWWWWWWWCO..",
    "..OWWWWWWWWWWWWWWWWCCO..",
    ".OWWOOWWWWWWWWWWWWOOCCO.",
    ".OWWOOWWWWWWWWWWWCOOCCO.",
    ".OWWWWWWWWWWWWWWCCCCCCO.",
    ".OWWWWWWOOWWWWOOCCCCCCO.",
    ".OWWWWWWOOWWWWOOCCCCCCO.",
    ".OWWWWWWWWWWWCCCCCCCCCO.",
    "OWWWWWWWWWWWCCCCCCCCCCCO",
    "OWCCWWWWWWWCCCCCCCCCCCCO",
    "OWCCWWWWWWCCCCCCCCCCCCCO",
    "OWCCWWWWWCCCCCCCCCCCCCCO",
    "OWCCWWWWCCCCCCCCCCCCCCCO",
    "OWCCOOWCCOOCCOOCCCOOCCCO",
    "OOOO..OOO..OO..OOO..OOOO",
    "........................",
    "........................",
]

STAR = [
    "........................",
    "..........OOOO..........",
    ".........OYYYYO.........",
    ".........OYYYYO.........",
    "........OYYYYYYO........",
    "........OYYYYYYO........",
    ".......OYYYYYYYYO.......",
    "OOOOOOOYYYYYYYYYYOOOOOOO",
    "OYYYYYYYYYYYYYYYYYYYYYYO",
    ".OYYYYYYYYYYYYYYYYYYYYO.",
    "..OYYYYYYYYYYYYYYYYYYO..",
    "...OYYOOYYYYYYYYOOYYO...",
    "...OYYOOYYYYYYYYOOYYO...",
    "...OYYYYYYYYYYYYYYYYO...",
    "...OYSSYOOYYYYOOYSSYO...",
    "...OYSSYYYYYYYYYYSSYO...",
    "....OSSSYYYYYYYYSSSO....",
    "....OSSSSSSSSSSSSSSO....",
    "...OSSSSSSSSSSSSSSSSO...",
    "..OSSSSOSSSSSSSSOSSSSO..",
    ".OSSSOOOSSSSSSSSOOOSSSO.",
    "OSSOO...OOSSSSOO...OOSSO",
    "OOO.......OOOO.......OOO",
    "........................",
]

CLOUD = [
    "........................",
    "........................",
    "........................",
    "........OOOOOOOO........",
    ".......OWWWWWWWWO.......",
    "....OOOWWWWWWWWWWOOO....",
    "...OWWWWWWWWWWWWWWWCO...",
    "..OWWWWWWWWWWWWWWWCCCO..",
    "..OWWWWWWWWWWWWWWCCCCO..",
    ".OWWWWWWWWWWWWWWCCCCCCO.",
    ".OWWOOWWWWWWWWWCCCOOCCO.",
    ".OWWOOWWWWWWWWCCCCOOCCO.",
    ".OWWWWWWWWWWWCCCCCCCCCO.",
    ".OWWPPWWOOWWCCOOCCPPCCO.",
    ".OWWPPWWOOWCCCOOCCPPCCO.",
    "OWWWWWWWWWCCCCCCCCCCCCCO",
    "OWWWWWWWWCCCCCCCCCCCCCCO",
    "OCCCCCCCCCCCCCCCCCCCCCCO",
    "OCCCCCCCCCCCCCCCCCCCCCCO",
    ".OCCCCCCCCCCCCCCCCCCCCO.",
    "..OOCCCCCCCCCCCCCCCCOO..",
    "....OOOOOOOOOOOOOOOO....",
    "........................",
    "........................",
]

AXOLOTL = [
    "........................",
    "........................",
    "..OO................OO..",
    ".ODDO...OOOOOOOO...ODDO.",
    ".ODDDOOOPPPPPPPPOOODDDO.",
    "..ODDDPPPPPPPPPPPPDDDO..",
    "OODDDPPPPPPPPPPPPPPDDDOO",
    "ODDDPPPPPPPPPPPPPPPPDDDO",
    "OODDDPPPPPPPPPPPPPPDDDOO",
    "..ODDDPPPPPPPPPPPPDDDO..",
    ".ODDDOOOPPPPPPPPOOODDDO.",
    ".ODDO..OPPPPPPPPO..ODDO.",
    "..OO...OPPPPPPPDO...OO..",
    ".......OPPOOOODDO.......",
    "......OPPPPPPDDDDO......",
    "......OPPPPPDDDDDO......",
    ".....OPPPPPDDDDDDDO.....",
    ".....OPPPPDDDDDDDDO.....",
    ".....OPPPDDDDDDDDDO.....",
    "......OPDDDDDDDDDO......",
    "......ODDDDDDDDDDO......",
    ".......OODDDDDDOO.......",
    ".........OOOOOO.........",
    "........................",
]

JELLYFISH = [
    "........................",
    "........................",
    "..........OOOO..........",
    ".......OOOCCCCOOO.......",
    ".....OOCCCCCCCCCCOO.....",
    "....OCCCCCCCCCCCCCCO....",
    "...OCCCCCCCCCCCCCCCBO...",
    "..OCCCCCCCCCCCCCCCBBBO..",
    "..OCCCCCCCCCCCCCCBBBBO..",
    ".OCCCCCCCCCCCCCCBBBBBBO.",
    ".OCCOOCCCCCCCCCBBBOOBBO.",
    ".OCCOOCCCCCCCCBBBBOOBBO.",
    ".OCCCCCCCCCCCBBBBBBBBBO.",
    ".OCCCCCCOOCCBBOOBBBBBBO.",
    "OCCCCCCCCCCBBBBBBBBBBBBO",
    "OBBBBBBBBBBBBBBBBBBBBBBO",
    "OOBBOOBBOOBBBBOOBBOOBBOO",
    ".OBBO.OBBO.OO.OBBO.OBBO.",
    ".OBBO.OBBO.OO.OBBO.OBBO.",
    "..OBBO.OBBO..OBBO.OBBO..",
    "..OBBO.OBBO..OBBO.OBBO..",
    "...OBO..OBO..OBO..OBO...",
    "...OOO..OOO..OOO..OOO...",
    "........................",
]

OWLET = [
    "........................",
    "...OO..............OO...",
    "..OKKO............OKKO..",
    "..OKKKOOOOOOOOOOOOKKKO..",
    "..OKKKKKKKKKKKKKKKKKKO..",
    ".OKKKKKKKKKKKKKKKKKKKKO.",
    ".OKHHHHOHHHHHHHHOHHHHKO.",
    "OKHHHHHOHHHHHHHHOHHHHHKO",
    "OKHOOHHOHHOOOOHHOHHOOHKO",
    "OKHOOHHOHHOOOOHHOHHOOHKO",
    "OKHHHHHOHHHHHHHHOHHHHHKO",
    "OKHHHHHOYYYYYYYYOHHHHHKO",
    "OKKHHHHHOYYYYYYOHHHHHKKO",
    "OKKKHHHHHHHHHHHHHHHHKKKO",
    ".OKKKKKKKKKKKKKKKKKKKKO.",
    ".OKKKHHHHKKKKKKHHHHKKKO.",
    ".OKKHHHHHHKKKKHHHHHHKKO.",
    ".OKKKHHHHKKKKKKHHHHKKKO.",
    "..OKKKKKKKKKKKKKKKKKKO..",
    "..OKKKKKKKKKKKKKKKKKKO..",
    "...OKKKKKKKKKKKKKKKKO...",
    "....OOOYYOOOOOOYYOOO....",
    "......OYYOYYYYOYYO......",
    "......OOOOOOOOOOOO......",
]

HEDGEHOG = [
    "........................",
    "..........OOOO..........",
    "........OOEEEEOO........",
    "......OOEEOEEOEEOO......",
    ".....OEEOEEEEEEOEEO.....",
    "....OEEEEOEEEEOEEEEO....",
    "...OEEOEEEEEEEEEEOEEO...",
    "..OEEEEEOEEEEEEOEEEEEO..",
    "..OEOEEEEEEEEEEEEEEOEO..",
    ".OEEEEEOEEEEEEEEOEEEEEO.",
    ".OEEEEEEEEOEEOEEEEEEEXO.",
    "OEEOEEEEEEEEEEEEEEEEOXXO",
    "OEEEEEEOEEEEEEEEOEEXXXXO",
    "OEEEEEEEEEEEEEEEEEXXXXXO",
    "OEEEEEEEEEEEEEEEEXXXXXXO",
    ".OEEEEEEEEEEEEEEXXXXXXO.",
    ".OEEHHHHHHHHHHHHHHHHXXO.",
    "..OEHHHHHHHHHHHHHHHHXO..",
    "..OHHHOOHHHHHHHHOOHHHO..",
    "..OHHHOOHHHHHHHHOOHHHO..",
    "...OHHHHHHHHHHHHHHHHO...",
    "...OHHHHHHOOOOHHHHHHO...",
    "....OOHHHHOOOOHHHHOO....",
    "......OOOOOOOOOOOO......",
]

UNICORN = [
    "........................",
    "...........OO...........",
    "..........OYYO..........",
    "..........OYYO..........",
    ".........OYYYYO.........",
    ".........OYYYYO.........",
    "......OOOOOOOOOOOO......",
    "....OOWWWWWWWWWWWWOO....",
    "...OWWWWWWWWWWWWWWWWO...",
    "..OWPWWWWWWWWWWWWWWPLO..",
    ".OWPPWWWWWWWWWWWWWWPPLO.",
    ".OWPPWWOOWWWWWWOOWLPPLO.",
    ".OWPPWWOOWWWWWWOOLLPPLO.",
    ".OWPPWWWWWWWWWWWLLLPPLO.",
    ".OWPPWWWWWWWWWWLLLLPPLO.",
    "..OWPWWWWWWWWWLLLLLPLO..",
    "..OWWWWWWWWWWLLLLLLLLO..",
    "..OWWWWWWWOPPOLLLLLLLO..",
    "..OWWWWWWWWLLLLLLLLLLO..",
    "...OWWWWWWLLLLLLLLLLO...",
    "...OWWWWWLLLLLLLLLLLO...",
    "....OWWWLLLLLLLLLLLO....",
    "....OOOOOOOOOOOOOOOO....",
    "........................",
]

SHEEP = [
    "........................",
    "........................",
    ".....OOOOOOOOOOOOOO.....",
    "...OOWWWWWWWWWWWWWWOO...",
    "..OWWWWWWWWWWWWWWWWWWO..",
    ".OWWWWWWWWWWWWWWWWWWWWO.",
    ".OWWOOOOOOOOOOOOOOOOWWO.",
    "OWWOXXXXXXXXXXXXXXXXOWWO",
    "OWWOXXXXXXXXXXXXXXXXOWWO",
    "OWWOXWWXXXXXXXXXXWWXOWWO",
    "OWWOXWOXXXXXXXXXXOWXOWWO",
    "OWWOXXXXXXXXXXXXXXXXOWWO",
    "OWWWOXXXXXXXXXXXXXXOWWWO",
    ".OWWWOOXXXXXXXXXXOOWWWO.",
    ".OWWWWWOOOOOOOOOOWWWWWO.",
    "OWWWWWWWWWWWWWWWWWWWWWWO",
    "OWWWWWWWWWWWWWWWWWWWWWWO",
    "OWWWWWWWWWWWWWWWWWWWWWWO",
    ".OWWWWWWWWWWWWWWWWWWWWO.",
    "..OWWWWWWWWWWWWWWWWWWO..",
    "...OOWWWWWWWWWWWWWWOO...",
    ".....OXXOOXXXXOOXXO.....",
    ".....OXXO.OXXO.OXXO.....",
    ".....OOOO.OOOO.OOOO.....",
]

FROG = [
    "........................",
    "........................",
    "......OOOO....OOOO......",
    ".....OGGGGO..OGGGGO.....",
    "....OGWWWGOOOOGWWWGO....",
    "....OGWOWGGGGGGWOWGO....",
    "...OGGWWWGGGGGGWWWGGO...",
    "...OGGGGGGGGGGGGGGGGO...",
    "..OGGGGGGGGGGGGGGGGGGO..",
    "..OGGGGGGGGGGGGGGGGGGO..",
    ".OGGGGGGGGGGGGGGGGGGGGO.",
    ".OGGGGGGGGGGGGGGGGGGGGO.",
    ".OGGGGGGGOOOOOOGGGGGGGO.",
    "OGGGGGGGGGGGGGGGGGGGGGGO",
    "OGNNNNNNNNNNNNNNNNNNNNGO",
    "OGNNNNNNNNNNNNNNNNNNNNGO",
    "ONNNNNNNNNNNNNNNNNNNNNNO",
    ".ONNNNNNNNNNNNNNNNNNNNO.",
    "..ONNNNNNNNNNNNNNNNNNO..",
    "OOONNNNNNNNNNNNNNNNNNOOO",
    "OGGOONNNNNNNNNNNNNNOOGGO",
    "OGGGOONNNNNNNNNNNNOOGGGO",
    "OOOOO.OOOOOOOOOOOO.OOOOO",
    "........................",
]

SNAIL = [
    "........................",
    ".........OOOOOO.........",
    ".......OOKKKKKKOO.......",
    "......OKKKEEEEKKKO......",
    ".....OKKEEOOOOEEKKO.....",
    ".....OKEEOKKKKOEEKO.....",
    "....OKKEOKKEEKKOEKKO....",
    "....OKEOKKEOOEKKOEKO....",
    "....OKEOKEOKKOEKOEKO....",
    "....OKEOKEOKKOEKOEKO....",
    "....OKEOKKEOOEKKOEKO....",
    "....OKKEOKKEEKKOEKKO....",
    ".....OKEEOKKKKOEEKO.....",
    ".OO..OKKEEOOOOEEKKO.....",
    "OIIO..OKKKEEEEKKKO......",
    "OIIO...OOKKKKKKOO.......",
    "OIIOOOOOOOOOOOOOOOO.....",
    "OIIIIIIIIIIIIIIIIIIO....",
    "OIIIIIIIIIIIIIIIIIIIO...",
    "OIIIIIIIIIIIIIIIIIIIIO..",
    ".OIIIIIIIIIIIIIIIIIIIO..",
    "..OOOOOOOOOOOOOOOOOOO...",
    "........................",
    "........................",
]

OCTOPUS = [
    "........................",
    "........................",
    "..........OOOO..........",
    ".......OOOVVVVOOO.......",
    ".....OOVVVVVVVVVVOO.....",
    "....OVVVVVVVVVVVVVVO....",
    "...OVVVVVVVVVVVVVVVJO...",
    "..OVVVVVVVVVVVVVVVJJJO..",
    "..OVVVVVVVVVVVVVVJJJJO..",
    ".OVVOOVVVVVVVVVVJJOOJJO.",
    ".OVVOOVVVVVVVVVJJJOOJJO.",
    ".OVVVVVVVVVVVVJJJJJJJJO.",
    ".OVVVVVVOOVVVJOOJJJJJJO.",
    "OVVVVVVVVVVVJJJJJJJJJJJO",
    "OVVVVVVVVVVJJJJJJJJJJJJO",
    "OJJJJJJJJJJJJJJJJJJJJJJO",
    "OOJJOOJJOOJJJJOOJJOOJJOO",
    ".OJJO.OJJO.OO.OJJO.OJJO.",
    ".OJJO.OJJO.OO.OJJO.OJJO.",
    "OJJO..OJJO....OJJO..OJJO",
    "OJJO..OJJOOOOOOJJO..OJJO",
    "OOO....OJJJJJJJJO....OOO",
    "........OOOOOOOO........",
    "........................",
]

TURTLE = [
    "........................",
    "........................",
    "........................",
    "........OOOOOOOO........",
    "......OONNNNNNNNOO......",
    ".....ONNNNNNNNNNNNO.....",
    "....ONNGGNNNNNNGGNNO....",
    "...ONNGGGGNNNNGGGGNNO...",
    "..ONNGGGGGGGGGGGGGGNNO..",
    "..ONGGGGNNGGGGNNGGGGNO..",
    ".ONGGNNGGGGGGGGGGNNGGNO.",
    ".ONGGGGGGGNNNNGGGGGGGNO.",
    ".ONGGGGNNGGGGGGNNGGGGNO.",
    "OONNGGGGGGGGGGGGGGGGNNOO",
    "OHHONNGGGGNNNNGGGGNNOHHO",
    "OHHHONNGGGGGGGGGGNNOHHHO",
    "OHWHHONNNNNNNNNNNNOHHWHO",
    "OHHHHHOOOOOOOOOOOOHHHHHO",
    ".OHHHHO..........OHHHHO.",
    "..OHHHO.OOOOOOOO.OHHHO..",
    "...OOOOOHHHHHHHHOOOOO...",
    ".......OHHHHHHHHO.......",
    ".......OOOOOOOOOO.......",
    "........................",
]

BAT = [
    "........................",
    "..OO................OO..",
    ".OJJO...OOOOOOOO...OJVO.",
    ".OJJJOOJJJJJJJJJJOOJVVO.",
    ".OJJJJJJJJJJJJJJJJJVVVO.",
    "..OJJJJJJJJJJJJJJJVVVO..",
    "..OJJJJJJJJJJJJJJVVVVO..",
    ".OJJOOJJJJJJJJJJVVOOVVO.",
    ".OJJOOJJJJJJJJJVVVOOVVO.",
    ".OJJJJJJJJJJJJVVVVVVVVO.",
    ".OJJJWWJJJJJJVVVVWWVVVO.",
    "OJJJJWWJJJJJVVVVVWWVVVVO",
    "OVVJJJJJJJJVVVVVVVVVVVVO",
    "OVVVJJJJJJVVVVVVVVVVVVVO",
    "OVVVVOJJJVVVVVVVVVOVVVVO",
    "OVVVVVOJVVVVVVVVVOVVVVVO",
    "OVVVVVVOVVVVVVVVOVVVVVVO",
    ".OVVVVVOVVVVVVVVOVVVVVO.",
    "..OVVVVOVVVVVVVVOVVVVO..",
    "...OVVVOVVVVVVVVOVVVO...",
    "....OVVOOVVVVVVOOVVO....",
    ".....OOO.OVVVVO.OOO.....",
    "..........OOOO..........",
    "........................",
]

CRITTERS = {
    "slime": SLIME,
    "chick": CHICK,
    "kitten": KITTEN,
    "bunny": BUNNY,
    "fox": FOX,
    "dragon": DRAGON,
    "ghost": GHOST,
    "star": STAR,
    "cloud": CLOUD,
    "axolotl": AXOLOTL,
    "jellyfish": JELLYFISH,
    "owlet": OWLET,
    "hedgehog": HEDGEHOG,
    "unicorn": UNICORN,
    "sheep": SHEEP,
    "frog": FROG,
    "snail": SNAIL,
    "octopus": OCTOPUS,
    "turtle": TURTLE,
    "bat": BAT,
}

SPRITES = {**ORIGINALS, **ZOO, **FRUIT, **CITY, **CRITTERS}
