#!/usr/bin/env python3
"""Writes the leaderboard's level table out of the levels the game ships.

    python3 scripts/seed_levels.py                  # SQL on stdout
    python3 scripts/seed_levels.py -o levels.sql    # SQL to a file

The worker measures every submission against a level's OptimalMoves, so it needs its own copy of
that number. This is where that copy comes from: the .tres files themselves, read with the same
parser scripts/update_par.py writes them with, so the two can never disagree about what a level's
optimal is.

Run on deploy rather than by hand. A new level, or one whose optimal was re-solved, then reaches
the server the next time the worker ships, and nothing has to remember to do it.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from sortpaint.level import read_campaign, read_level_tres

ROOT = Path(__file__).resolve().parent.parent
LEVELS = ROOT / "levels"
CAMPAIGN = LEVELS / "campaign.tres"


def rows():
    """Every campaign level as (slug, optimal_moves), in menu order."""
    found = []
    for name in read_campaign(CAMPAIGN):
        path = LEVELS / f"{name}.tres"
        if not path.exists():
            raise SystemExit(f"campaign.tres lists {name}, but {path} is not there")

        found.append((name, read_level_tres(path)["optimal_moves"]))

    return found


def sql(levels):
    """The statements that make the levels table match the game, and nothing else touch it."""
    # No BEGIN TRANSACTION or COMMIT: D1 refuses them in an imported file, and does not need them.
    # An import that fails leaves the database as it was, so the batch is already all or nothing.
    lines = [
        "-- Generated by scripts/seed_levels.py. Do not edit; re-run it instead.",
        "-- Applied on every worker deploy, so a re-solved optimal reaches the server by itself.",
    ]

    for slug, optimal in levels:
        # A level that is already there has its optimal brought up to date rather than duplicated.
        lines.append(
            f"INSERT INTO levels (slug, optimal) VALUES ('{slug}', {optimal}) "
            f"ON CONFLICT(slug) DO UPDATE SET optimal = excluded.optimal;"
        )

    # A level pulled from the campaign stops being scoreable, but the rounds people already played
    # on it are left alone: deleting their rows would be throwing away somebody's record.
    keep = ", ".join(f"'{slug}'" for slug, _ in levels)
    lines.append(f"DELETE FROM levels WHERE slug NOT IN ({keep});")

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-o", "--out", type=Path, help="where to write the SQL, instead of stdout")
    args = parser.parse_args()

    levels = rows()
    if not levels:
        raise SystemExit("campaign.tres offered no levels, which cannot be right")

    text = sql(levels)

    if args.out:
        args.out.write_text(text)
        print(f"{len(levels)} levels written to {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
